// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.HubSpot.OpenApiClient.Settings.Currencies.TwoZeroTwoSixZeroThree.CentralFxRates.AddCurrency;
using Soenneker.HubSpot.OpenApiClient.Settings.Currencies.TwoZeroTwoSixZeroThree.CentralFxRates.Information;
using Soenneker.HubSpot.OpenApiClient.Settings.Currencies.TwoZeroTwoSixZeroThree.CentralFxRates.UnsupportedCurrencies;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Settings.Currencies.TwoZeroTwoSixZeroThree.CentralFxRates
{
    /// <summary>
    /// Builds and executes requests for operations under \settings\currencies\2026-03\central-fx-rates
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CentralFxRatesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The addCurrency property</summary>
        public global::Soenneker.HubSpot.OpenApiClient.Settings.Currencies.TwoZeroTwoSixZeroThree.CentralFxRates.AddCurrency.AddCurrencyRequestBuilder AddCurrency
        {
            get => new global::Soenneker.HubSpot.OpenApiClient.Settings.Currencies.TwoZeroTwoSixZeroThree.CentralFxRates.AddCurrency.AddCurrencyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The information property</summary>
        public global::Soenneker.HubSpot.OpenApiClient.Settings.Currencies.TwoZeroTwoSixZeroThree.CentralFxRates.Information.InformationRequestBuilder Information
        {
            get => new global::Soenneker.HubSpot.OpenApiClient.Settings.Currencies.TwoZeroTwoSixZeroThree.CentralFxRates.Information.InformationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The unsupportedCurrencies property</summary>
        public global::Soenneker.HubSpot.OpenApiClient.Settings.Currencies.TwoZeroTwoSixZeroThree.CentralFxRates.UnsupportedCurrencies.UnsupportedCurrenciesRequestBuilder UnsupportedCurrencies
        {
            get => new global::Soenneker.HubSpot.OpenApiClient.Settings.Currencies.TwoZeroTwoSixZeroThree.CentralFxRates.UnsupportedCurrencies.UnsupportedCurrenciesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HubSpot.OpenApiClient.Settings.Currencies.TwoZeroTwoSixZeroThree.CentralFxRates.CentralFxRatesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CentralFxRatesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/settings/currencies/2026-03/central-fx-rates", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HubSpot.OpenApiClient.Settings.Currencies.TwoZeroTwoSixZeroThree.CentralFxRates.CentralFxRatesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CentralFxRatesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/settings/currencies/2026-03/central-fx-rates", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
