// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.HubSpot.OpenApiClient.Cms.SourceCode.TwoZeroTwoSixZeroThree.Item.Validate.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Cms.SourceCode.TwoZeroTwoSixZeroThree.Item.Validate
{
    /// <summary>
    /// Builds and executes requests for operations under \cms\source-code\2026-03\{environment}\validate
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ValidateRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.HubSpot.OpenApiClient.cms.sourceCode.TwoZeroTwoSixZeroThree.item.validate.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.HubSpot.OpenApiClient.Cms.SourceCode.TwoZeroTwoSixZeroThree.Item.Validate.Item.WithPathItemRequestBuilder"/></returns>
        public global::Soenneker.HubSpot.OpenApiClient.Cms.SourceCode.TwoZeroTwoSixZeroThree.Item.Validate.Item.WithPathItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("path", position);
                return new global::Soenneker.HubSpot.OpenApiClient.Cms.SourceCode.TwoZeroTwoSixZeroThree.Item.Validate.Item.WithPathItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HubSpot.OpenApiClient.Cms.SourceCode.TwoZeroTwoSixZeroThree.Item.Validate.ValidateRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ValidateRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/cms/source-code/2026-03/{environment}/validate", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HubSpot.OpenApiClient.Cms.SourceCode.TwoZeroTwoSixZeroThree.Item.Validate.ValidateRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ValidateRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/cms/source-code/2026-03/{environment}/validate", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
