// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.HubSpot.OpenApiClient.Crm.PipelinesRules.TwoZeroTwoSixZeroNine;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Crm.PipelinesRules
{
    /// <summary>
    /// Builds and executes requests for operations under \crm\pipelines-rules
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PipelinesRulesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The TwoZeroTwoSixZeroNine property</summary>
        public global::Soenneker.HubSpot.OpenApiClient.Crm.PipelinesRules.TwoZeroTwoSixZeroNine.TwoZeroTwoSixZeroNineRequestBuilder TwoZeroTwoSixZeroNine
        {
            get => new global::Soenneker.HubSpot.OpenApiClient.Crm.PipelinesRules.TwoZeroTwoSixZeroNine.TwoZeroTwoSixZeroNineRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HubSpot.OpenApiClient.Crm.PipelinesRules.PipelinesRulesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PipelinesRulesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/crm/pipelines-rules", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HubSpot.OpenApiClient.Crm.PipelinesRules.PipelinesRulesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PipelinesRulesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/crm/pipelines-rules", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
