// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    /// <summary>A string indicating the type of comparison to be made with the timestamp. Valid values are &apos;BEFORE&apos; and &apos;AFTER&apos;.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AbsoluteComparativeTimestampRefineByComparison
    {
        [EnumMember(Value = "AFTER")]
        #pragma warning disable CS1591
        After,
        #pragma warning restore CS1591
        [EnumMember(Value = "BEFORE")]
        #pragma warning disable CS1591
        Before,
        #pragma warning restore CS1591
    }
}
