// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.ApiFlowBatchFetchMigrationFlowIdCoordinate"/>, <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.ApiFlowBatchFetchMigrationWorkflowIdCoordinate"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiFlowBatchMigrationInputInputsItem : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.ApiFlowBatchFetchMigrationFlowIdCoordinate"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HubSpot.OpenApiClient.Models.ApiFlowBatchFetchMigrationFlowIdCoordinate? ApiFlowBatchFetchMigrationFlowIdCoordinate { get; set; }
#nullable restore
#else
        public global::Soenneker.HubSpot.OpenApiClient.Models.ApiFlowBatchFetchMigrationFlowIdCoordinate ApiFlowBatchFetchMigrationFlowIdCoordinate { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.ApiFlowBatchFetchMigrationWorkflowIdCoordinate"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HubSpot.OpenApiClient.Models.ApiFlowBatchFetchMigrationWorkflowIdCoordinate? ApiFlowBatchFetchMigrationWorkflowIdCoordinate { get; set; }
#nullable restore
#else
        public global::Soenneker.HubSpot.OpenApiClient.Models.ApiFlowBatchFetchMigrationWorkflowIdCoordinate ApiFlowBatchFetchMigrationWorkflowIdCoordinate { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.ApiFlowBatchMigrationInputInputsItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HubSpot.OpenApiClient.Models.ApiFlowBatchMigrationInputInputsItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.HubSpot.OpenApiClient.Models.ApiFlowBatchMigrationInputInputsItem();
            if("ApiFlowBatchFetchMigrationFlowIdCoordinate".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ApiFlowBatchFetchMigrationFlowIdCoordinate = new global::Soenneker.HubSpot.OpenApiClient.Models.ApiFlowBatchFetchMigrationFlowIdCoordinate();
            }
            else if("ApiFlowBatchFetchMigrationWorkflowIdCoordinate".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ApiFlowBatchFetchMigrationWorkflowIdCoordinate = new global::Soenneker.HubSpot.OpenApiClient.Models.ApiFlowBatchFetchMigrationWorkflowIdCoordinate();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ApiFlowBatchFetchMigrationFlowIdCoordinate != null)
            {
                return ApiFlowBatchFetchMigrationFlowIdCoordinate.GetFieldDeserializers();
            }
            else if(ApiFlowBatchFetchMigrationWorkflowIdCoordinate != null)
            {
                return ApiFlowBatchFetchMigrationWorkflowIdCoordinate.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(ApiFlowBatchFetchMigrationFlowIdCoordinate != null)
            {
                writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.ApiFlowBatchFetchMigrationFlowIdCoordinate>(null, ApiFlowBatchFetchMigrationFlowIdCoordinate);
            }
            else if(ApiFlowBatchFetchMigrationWorkflowIdCoordinate != null)
            {
                writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.ApiFlowBatchFetchMigrationWorkflowIdCoordinate>(null, ApiFlowBatchFetchMigrationWorkflowIdCoordinate);
            }
        }
    }
}
#pragma warning restore CS0618
