// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.ApiDatasetBasedEnrollmentCriteria"/>, <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.ApiEventBasedEnrollmentCriteria"/>, <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.ApiListBasedEnrollmentCriteria"/>, <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.ApiManualEnrollmentCriteria"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiPlatformFlowEnrollmentCriteria : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.ApiDatasetBasedEnrollmentCriteria"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HubSpot.OpenApiClient.Models.ApiDatasetBasedEnrollmentCriteria? ApiDatasetBasedEnrollmentCriteria { get; set; }
#nullable restore
#else
        public global::Soenneker.HubSpot.OpenApiClient.Models.ApiDatasetBasedEnrollmentCriteria ApiDatasetBasedEnrollmentCriteria { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.ApiEventBasedEnrollmentCriteria"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HubSpot.OpenApiClient.Models.ApiEventBasedEnrollmentCriteria? ApiEventBasedEnrollmentCriteria { get; set; }
#nullable restore
#else
        public global::Soenneker.HubSpot.OpenApiClient.Models.ApiEventBasedEnrollmentCriteria ApiEventBasedEnrollmentCriteria { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.ApiListBasedEnrollmentCriteria"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HubSpot.OpenApiClient.Models.ApiListBasedEnrollmentCriteria? ApiListBasedEnrollmentCriteria { get; set; }
#nullable restore
#else
        public global::Soenneker.HubSpot.OpenApiClient.Models.ApiListBasedEnrollmentCriteria ApiListBasedEnrollmentCriteria { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.ApiManualEnrollmentCriteria"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HubSpot.OpenApiClient.Models.ApiManualEnrollmentCriteria? ApiManualEnrollmentCriteria { get; set; }
#nullable restore
#else
        public global::Soenneker.HubSpot.OpenApiClient.Models.ApiManualEnrollmentCriteria ApiManualEnrollmentCriteria { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.ApiPlatformFlowEnrollmentCriteria"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HubSpot.OpenApiClient.Models.ApiPlatformFlowEnrollmentCriteria CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.HubSpot.OpenApiClient.Models.ApiPlatformFlowEnrollmentCriteria();
            if("ApiDatasetBasedEnrollmentCriteria".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ApiDatasetBasedEnrollmentCriteria = new global::Soenneker.HubSpot.OpenApiClient.Models.ApiDatasetBasedEnrollmentCriteria();
            }
            else if("ApiEventBasedEnrollmentCriteria".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ApiEventBasedEnrollmentCriteria = new global::Soenneker.HubSpot.OpenApiClient.Models.ApiEventBasedEnrollmentCriteria();
            }
            else if("ApiListBasedEnrollmentCriteria".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ApiListBasedEnrollmentCriteria = new global::Soenneker.HubSpot.OpenApiClient.Models.ApiListBasedEnrollmentCriteria();
            }
            else if("ApiManualEnrollmentCriteria".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ApiManualEnrollmentCriteria = new global::Soenneker.HubSpot.OpenApiClient.Models.ApiManualEnrollmentCriteria();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ApiDatasetBasedEnrollmentCriteria != null)
            {
                return ApiDatasetBasedEnrollmentCriteria.GetFieldDeserializers();
            }
            else if(ApiEventBasedEnrollmentCriteria != null)
            {
                return ApiEventBasedEnrollmentCriteria.GetFieldDeserializers();
            }
            else if(ApiListBasedEnrollmentCriteria != null)
            {
                return ApiListBasedEnrollmentCriteria.GetFieldDeserializers();
            }
            else if(ApiManualEnrollmentCriteria != null)
            {
                return ApiManualEnrollmentCriteria.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(ApiDatasetBasedEnrollmentCriteria != null)
            {
                writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.ApiDatasetBasedEnrollmentCriteria>(null, ApiDatasetBasedEnrollmentCriteria);
            }
            else if(ApiEventBasedEnrollmentCriteria != null)
            {
                writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.ApiEventBasedEnrollmentCriteria>(null, ApiEventBasedEnrollmentCriteria);
            }
            else if(ApiListBasedEnrollmentCriteria != null)
            {
                writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.ApiListBasedEnrollmentCriteria>(null, ApiListBasedEnrollmentCriteria);
            }
            else if(ApiManualEnrollmentCriteria != null)
            {
                writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.ApiManualEnrollmentCriteria>(null, ApiManualEnrollmentCriteria);
            }
        }
    }
}
#pragma warning restore CS0618
