// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    /// <summary>Specifies the type of unenrollment setting, with possible values being ALL or SELECTIVE.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ApiUnEnrollmentSetting_type
    {
        [EnumMember(Value = "ALL")]
        #pragma warning disable CS1591
        ALL,
        #pragma warning restore CS1591
        [EnumMember(Value = "SELECTIVE")]
        #pragma warning disable CS1591
        SELECTIVE,
        #pragma warning restore CS1591
    }
}
