// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    /// <summary>Indicates the type of action, which defaults to WEBHOOK.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ApiWebhookAction_type
    {
        [EnumMember(Value = "WEBHOOK")]
        #pragma warning disable CS1591
        WEBHOOK,
        #pragma warning restore CS1591
    }
}
