// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Automation_Automation_V4_ApiFetchedObjectPropertyValue : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The token used to identify the specific property of the fetched object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PropertyToken { get; set; }
#nullable restore
#else
        public string PropertyToken { get; set; }
#endif
        /// <summary>Indicates the type of the fetched object property, which defaults to FETCHED_OBJECT_PROPERTY.</summary>
        public global::Soenneker.HubSpot.OpenApiClient.Models.Automation_Automation_V4_ApiFetchedObjectPropertyValue_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.Automation_Automation_V4_ApiFetchedObjectPropertyValue"/> and sets the default values.
        /// </summary>
        public Automation_Automation_V4_ApiFetchedObjectPropertyValue()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.Automation_Automation_V4_ApiFetchedObjectPropertyValue"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HubSpot.OpenApiClient.Models.Automation_Automation_V4_ApiFetchedObjectPropertyValue CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HubSpot.OpenApiClient.Models.Automation_Automation_V4_ApiFetchedObjectPropertyValue();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "propertyToken", n => { PropertyToken = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.Automation_Automation_V4_ApiFetchedObjectPropertyValue_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("propertyToken", PropertyToken);
            writer.WriteEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.Automation_Automation_V4_ApiFetchedObjectPropertyValue_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
