// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Automation_Automation_V4_ApiTimeDelay : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The daysOfWeek property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.HubSpot.OpenApiClient.Models.Automation_Automation_V4_ApiTimeDelay_daysOfWeek?>? DaysOfWeek { get; set; }
#nullable restore
#else
        public List<global::Soenneker.HubSpot.OpenApiClient.Models.Automation_Automation_V4_ApiTimeDelay_daysOfWeek?> DaysOfWeek { get; set; }
#endif
        /// <summary>The amount of time to delay, specified as an integer.</summary>
        public int? Delta { get; set; }
        /// <summary>The timeOfDay property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HubSpot.OpenApiClient.Models.Automation_Automation_V4_ApiTimeOfDay? TimeOfDay { get; set; }
#nullable restore
#else
        public global::Soenneker.HubSpot.OpenApiClient.Models.Automation_Automation_V4_ApiTimeOfDay TimeOfDay { get; set; }
#endif
        /// <summary>&quot;Defines the unit of time for the delay, with accepted values including: CENTURIES, DAYS, DECADES, ERAS, FOREVER, HALF_DAYS, HOURS, MICROS, MILLENNIA, MILLIS, MINUTES, MONTHS, NANOS, SECONDS, WEEKS, YEARS.&quot;</summary>
        public global::Soenneker.HubSpot.OpenApiClient.Models.Automation_Automation_V4_ApiTimeDelay_timeUnit? TimeUnit { get; set; }
        /// <summary>Specifies the strategy for determining the time zone for the delay.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HubSpot.OpenApiClient.Models.Automation_Automation_V4_ApiTimeDelay_timeZoneStrategy? TimeZoneStrategy { get; set; }
#nullable restore
#else
        public global::Soenneker.HubSpot.OpenApiClient.Models.Automation_Automation_V4_ApiTimeDelay_timeZoneStrategy TimeZoneStrategy { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.Automation_Automation_V4_ApiTimeDelay"/> and sets the default values.
        /// </summary>
        public Automation_Automation_V4_ApiTimeDelay()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.Automation_Automation_V4_ApiTimeDelay"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HubSpot.OpenApiClient.Models.Automation_Automation_V4_ApiTimeDelay CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HubSpot.OpenApiClient.Models.Automation_Automation_V4_ApiTimeDelay();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "daysOfWeek", n => { DaysOfWeek = n.GetCollectionOfEnumValues<global::Soenneker.HubSpot.OpenApiClient.Models.Automation_Automation_V4_ApiTimeDelay_daysOfWeek>()?.AsList(); } },
                { "delta", n => { Delta = n.GetIntValue(); } },
                { "timeOfDay", n => { TimeOfDay = n.GetObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.Automation_Automation_V4_ApiTimeOfDay>(global::Soenneker.HubSpot.OpenApiClient.Models.Automation_Automation_V4_ApiTimeOfDay.CreateFromDiscriminatorValue); } },
                { "timeUnit", n => { TimeUnit = n.GetEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.Automation_Automation_V4_ApiTimeDelay_timeUnit>(); } },
                { "timeZoneStrategy", n => { TimeZoneStrategy = n.GetObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.Automation_Automation_V4_ApiTimeDelay_timeZoneStrategy>(global::Soenneker.HubSpot.OpenApiClient.Models.Automation_Automation_V4_ApiTimeDelay_timeZoneStrategy.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfEnumValues<global::Soenneker.HubSpot.OpenApiClient.Models.Automation_Automation_V4_ApiTimeDelay_daysOfWeek>("daysOfWeek", DaysOfWeek);
            writer.WriteIntValue("delta", Delta);
            writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.Automation_Automation_V4_ApiTimeOfDay>("timeOfDay", TimeOfDay);
            writer.WriteEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.Automation_Automation_V4_ApiTimeDelay_timeUnit>("timeUnit", TimeUnit);
            writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.Automation_Automation_V4_ApiTimeDelay_timeZoneStrategy>("timeZoneStrategy", TimeZoneStrategy);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
