// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    /// <summary>Indicates the type of the action, which defaults to APPEND_OBJECT_PROPERTY.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Automation_Automation_V4_ApiAppendObjectPropertyValue_type
    {
        [EnumMember(Value = "APPEND_OBJECT_PROPERTY")]
        #pragma warning disable CS1591
        APPEND_OBJECT_PROPERTY,
        #pragma warning restore CS1591
    }
}
