// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum C__crm_AssociationSpec_associationCategory
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "HUBSPOT_DEFINED")]
        #pragma warning disable CS1591
        HUBSPOT_DEFINED,
        #pragma warning restore CS1591
        [EnumMember(Value = "USER_DEFINED")]
        #pragma warning disable CS1591
        USER_DEFINED,
        #pragma warning restore CS1591
        [EnumMember(Value = "INTEGRATOR_DEFINED")]
        #pragma warning disable CS1591
        INTEGRATOR_DEFINED,
        #pragma warning restore CS1591
    }
}
