// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CMS_Media_Bridge_PropertyCreate : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The calculationFormula property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CalculationFormula { get; set; }
#nullable restore
#else
        public string CalculationFormula { get; set; }
#endif
        /// <summary>The dataSensitivity property</summary>
        public global::Soenneker.HubSpot.OpenApiClient.Models.CMS_Media_Bridge_PropertyCreate_dataSensitivity? DataSensitivity { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The displayOrder property</summary>
        public int? DisplayOrder { get; set; }
        /// <summary>The externalOptions property</summary>
        public bool? ExternalOptions { get; set; }
        /// <summary>The fieldType property</summary>
        public global::Soenneker.HubSpot.OpenApiClient.Models.CMS_Media_Bridge_PropertyCreate_fieldType? FieldType { get; set; }
        /// <summary>The formField property</summary>
        public bool? FormField { get; set; }
        /// <summary>The groupName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupName { get; set; }
#nullable restore
#else
        public string GroupName { get; set; }
#endif
        /// <summary>The hasUniqueValue property</summary>
        public bool? HasUniqueValue { get; set; }
        /// <summary>The hidden property</summary>
        public bool? Hidden { get; set; }
        /// <summary>The label property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Label { get; set; }
#nullable restore
#else
        public string Label { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The options property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.HubSpot.OpenApiClient.Models.CMS_Media_Bridge_OptionInput>? Options { get; set; }
#nullable restore
#else
        public List<global::Soenneker.HubSpot.OpenApiClient.Models.CMS_Media_Bridge_OptionInput> Options { get; set; }
#endif
        /// <summary>The referencedObjectType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReferencedObjectType { get; set; }
#nullable restore
#else
        public string ReferencedObjectType { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.HubSpot.OpenApiClient.Models.CMS_Media_Bridge_PropertyCreate_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.CMS_Media_Bridge_PropertyCreate"/> and sets the default values.
        /// </summary>
        public CMS_Media_Bridge_PropertyCreate()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.CMS_Media_Bridge_PropertyCreate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HubSpot.OpenApiClient.Models.CMS_Media_Bridge_PropertyCreate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HubSpot.OpenApiClient.Models.CMS_Media_Bridge_PropertyCreate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "calculationFormula", n => { CalculationFormula = n.GetStringValue(); } },
                { "dataSensitivity", n => { DataSensitivity = n.GetEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.CMS_Media_Bridge_PropertyCreate_dataSensitivity>(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "displayOrder", n => { DisplayOrder = n.GetIntValue(); } },
                { "externalOptions", n => { ExternalOptions = n.GetBoolValue(); } },
                { "fieldType", n => { FieldType = n.GetEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.CMS_Media_Bridge_PropertyCreate_fieldType>(); } },
                { "formField", n => { FormField = n.GetBoolValue(); } },
                { "groupName", n => { GroupName = n.GetStringValue(); } },
                { "hasUniqueValue", n => { HasUniqueValue = n.GetBoolValue(); } },
                { "hidden", n => { Hidden = n.GetBoolValue(); } },
                { "label", n => { Label = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "options", n => { Options = n.GetCollectionOfObjectValues<global::Soenneker.HubSpot.OpenApiClient.Models.CMS_Media_Bridge_OptionInput>(global::Soenneker.HubSpot.OpenApiClient.Models.CMS_Media_Bridge_OptionInput.CreateFromDiscriminatorValue)?.AsList(); } },
                { "referencedObjectType", n => { ReferencedObjectType = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.CMS_Media_Bridge_PropertyCreate_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("calculationFormula", CalculationFormula);
            writer.WriteEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.CMS_Media_Bridge_PropertyCreate_dataSensitivity>("dataSensitivity", DataSensitivity);
            writer.WriteStringValue("description", Description);
            writer.WriteIntValue("displayOrder", DisplayOrder);
            writer.WriteBoolValue("externalOptions", ExternalOptions);
            writer.WriteEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.CMS_Media_Bridge_PropertyCreate_fieldType>("fieldType", FieldType);
            writer.WriteBoolValue("formField", FormField);
            writer.WriteStringValue("groupName", GroupName);
            writer.WriteBoolValue("hasUniqueValue", HasUniqueValue);
            writer.WriteBoolValue("hidden", Hidden);
            writer.WriteStringValue("label", Label);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfObjectValues<global::Soenneker.HubSpot.OpenApiClient.Models.CMS_Media_Bridge_OptionInput>("options", Options);
            writer.WriteStringValue("referencedObjectType", ReferencedObjectType);
            writer.WriteEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.CMS_Media_Bridge_PropertyCreate_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
