// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    /// <summary>The type of client interacting with the API. Valid values include &apos;HUBSPOT&apos;, &apos;SYSTEM&apos;, &apos;INTEGRATION&apos;, and &apos;UNKNOWN&apos;.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ConversationsPublicClientClientType
    {
        [EnumMember(Value = "HUBSPOT")]
        #pragma warning disable CS1591
        Hubspot,
        #pragma warning restore CS1591
        [EnumMember(Value = "INTEGRATION")]
        #pragma warning disable CS1591
        Integration,
        #pragma warning restore CS1591
        [EnumMember(Value = "SYSTEM")]
        #pragma warning disable CS1591
        System,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNKNOWN")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
    }
}
