// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    /// <summary>Specifies the type of refinement, (RELATIVE_COMPARATIVE).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CRM_Lists_PublicRelativeComparativeTimestampRefineBy_type
    {
        [EnumMember(Value = "RELATIVE_COMPARATIVE")]
        #pragma warning disable CS1591
        RELATIVE_COMPARATIVE,
        #pragma warning restore CS1591
    }
}
