// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    /// <summary>Specifies the type of operation (BOOL).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CRM_Lists_PublicBoolPropertyOperation_operationType
    {
        [EnumMember(Value = "BOOL")]
        #pragma warning disable CS1591
        BOOL,
        #pragma warning restore CS1591
    }
}
