// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CRM_Limits_Tracking_CustomObjectRecordLimitResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The byObjectType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.HubSpot.OpenApiClient.Models.CRM_Limits_Tracking_UsageForObjectType>? ByObjectType { get; set; }
#nullable restore
#else
        public List<global::Soenneker.HubSpot.OpenApiClient.Models.CRM_Limits_Tracking_UsageForObjectType> ByObjectType { get; set; }
#endif
        /// <summary>The maximum number of custom object records allowed.</summary>
        public int? OverallLimit { get; set; }
        /// <summary>The percentage of the overall custom object record limit that has been used.</summary>
        public double? OverallPercentage { get; set; }
        /// <summary>The total number of custom object records currently in use.</summary>
        public int? OverallUsage { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.CRM_Limits_Tracking_CustomObjectRecordLimitResponse"/> and sets the default values.
        /// </summary>
        public CRM_Limits_Tracking_CustomObjectRecordLimitResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.CRM_Limits_Tracking_CustomObjectRecordLimitResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HubSpot.OpenApiClient.Models.CRM_Limits_Tracking_CustomObjectRecordLimitResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HubSpot.OpenApiClient.Models.CRM_Limits_Tracking_CustomObjectRecordLimitResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "byObjectType", n => { ByObjectType = n.GetCollectionOfObjectValues<global::Soenneker.HubSpot.OpenApiClient.Models.CRM_Limits_Tracking_UsageForObjectType>(global::Soenneker.HubSpot.OpenApiClient.Models.CRM_Limits_Tracking_UsageForObjectType.CreateFromDiscriminatorValue)?.AsList(); } },
                { "overallLimit", n => { OverallLimit = n.GetIntValue(); } },
                { "overallPercentage", n => { OverallPercentage = n.GetDoubleValue(); } },
                { "overallUsage", n => { OverallUsage = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.HubSpot.OpenApiClient.Models.CRM_Limits_Tracking_UsageForObjectType>("byObjectType", ByObjectType);
            writer.WriteIntValue("overallLimit", OverallLimit);
            writer.WriteDoubleValue("overallPercentage", OverallPercentage);
            writer.WriteIntValue("overallUsage", OverallUsage);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
