// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    /// <summary>A string representing the type of filter. It is a required field and typically has a default value specific to the filter type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CrmIntegrationEventFilterType2
    {
        [EnumMember(Value = "INTEGRATION_EVENT")]
        #pragma warning disable CS1591
        IntegrationEvent,
        #pragma warning restore CS1591
    }
}
