// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    /// <summary>Controls how date properties are displayed in the HubSpot UI, with options such as &apos;absolute&apos;, &apos;absolute_with_relative&apos;, &apos;time_since&apos;, and &apos;time_until&apos;.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CrmObjectSchemasPropertyDateDisplayHint
    {
        [EnumMember(Value = "absolute")]
        #pragma warning disable CS1591
        Absolute,
        #pragma warning restore CS1591
        [EnumMember(Value = "absolute_with_relative")]
        #pragma warning disable CS1591
        AbsoluteWithRelative,
        #pragma warning restore CS1591
        [EnumMember(Value = "time_since")]
        #pragma warning disable CS1591
        TimeSince,
        #pragma warning restore CS1591
        [EnumMember(Value = "time_until")]
        #pragma warning disable CS1591
        TimeUntil,
        #pragma warning restore CS1591
    }
}
