// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CrmPublicPageViewAnalyticsFilter : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Specifies the criteria for refining the filter by coalescing.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HubSpot.OpenApiClient.Models.CrmPublicPageViewAnalyticsFilterCoalescingRefineBy? CoalescingRefineBy { get; set; }
#nullable restore
#else
        public global::Soenneker.HubSpot.OpenApiClient.Models.CrmPublicPageViewAnalyticsFilterCoalescingRefineBy CoalescingRefineBy { get; set; }
#endif
        /// <summary>Indicates whether tracking is enabled for the page view.</summary>
        public bool? EnableTracking { get; set; }
        /// <summary>Indicates the type of filter being applied (PAGE_VIEW).</summary>
        public global::Soenneker.HubSpot.OpenApiClient.Models.CrmPublicPageViewAnalyticsFilter_filterType? FilterType { get; set; }
        /// <summary>Defines the operation to be applied within the filter (HAS_PAGEVIEW_EQ, HAS_PAGEVIEW_CONTAINS, HAS_PAGEVIEW_MATCHES_REGEX, NOT_HAS_PAGEVIEW_EQ, NOT_HAS_PAGEVIEW_CONTAINS).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Operator { get; set; }
#nullable restore
#else
        public string Operator { get; set; }
#endif
        /// <summary>The URL of the page to be used in the filter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PageUrl { get; set; }
#nullable restore
#else
        public string PageUrl { get; set; }
#endif
        /// <summary>Specifies the criteria for refining the filter by pruning.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HubSpot.OpenApiClient.Models.CrmPublicPageViewAnalyticsFilterPruningRefineBy? PruningRefineBy { get; set; }
#nullable restore
#else
        public global::Soenneker.HubSpot.OpenApiClient.Models.CrmPublicPageViewAnalyticsFilterPruningRefineBy PruningRefineBy { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.CrmPublicPageViewAnalyticsFilter"/> and sets the default values.
        /// </summary>
        public CrmPublicPageViewAnalyticsFilter()
        {
            AdditionalData = new Dictionary<string, object>();
            FilterType = global::Soenneker.HubSpot.OpenApiClient.Models.CrmPublicPageViewAnalyticsFilter_filterType.PAGE_VIEW;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.CrmPublicPageViewAnalyticsFilter"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HubSpot.OpenApiClient.Models.CrmPublicPageViewAnalyticsFilter CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HubSpot.OpenApiClient.Models.CrmPublicPageViewAnalyticsFilter();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "coalescingRefineBy", n => { CoalescingRefineBy = n.GetObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.CrmPublicPageViewAnalyticsFilterCoalescingRefineBy>(global::Soenneker.HubSpot.OpenApiClient.Models.CrmPublicPageViewAnalyticsFilterCoalescingRefineBy.CreateFromDiscriminatorValue); } },
                { "enableTracking", n => { EnableTracking = n.GetBoolValue(); } },
                { "filterType", n => { FilterType = n.GetEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.CrmPublicPageViewAnalyticsFilter_filterType>(); } },
                { "operator", n => { Operator = n.GetStringValue(); } },
                { "pageUrl", n => { PageUrl = n.GetStringValue(); } },
                { "pruningRefineBy", n => { PruningRefineBy = n.GetObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.CrmPublicPageViewAnalyticsFilterPruningRefineBy>(global::Soenneker.HubSpot.OpenApiClient.Models.CrmPublicPageViewAnalyticsFilterPruningRefineBy.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.CrmPublicPageViewAnalyticsFilterCoalescingRefineBy>("coalescingRefineBy", CoalescingRefineBy);
            writer.WriteBoolValue("enableTracking", EnableTracking);
            writer.WriteEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.CrmPublicPageViewAnalyticsFilter_filterType>("filterType", FilterType);
            writer.WriteStringValue("operator", Operator);
            writer.WriteStringValue("pageUrl", PageUrl);
            writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.CrmPublicPageViewAnalyticsFilterPruningRefineBy>("pruningRefineBy", PruningRefineBy);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
