// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CrmPublicInListFilter : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Indicates the type of filter being applied (IN_LIST).</summary>
        public global::Soenneker.HubSpot.OpenApiClient.Models.CrmPublicInListFilter_filterType? FilterType { get; set; }
        /// <summary>The ID of the list used in the association filter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ListId { get; set; }
#nullable restore
#else
        public string ListId { get; set; }
#endif
        /// <summary>The metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HubSpot.OpenApiClient.Models.CrmPublicInListFilterMetadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.HubSpot.OpenApiClient.Models.CrmPublicInListFilterMetadata Metadata { get; set; }
#endif
        /// <summary>Specifies the operation to be performed by the filter (IN_LIST, NOT_IN_LIST).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Operator { get; set; }
#nullable restore
#else
        public string Operator { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.CrmPublicInListFilter"/> and sets the default values.
        /// </summary>
        public CrmPublicInListFilter()
        {
            AdditionalData = new Dictionary<string, object>();
            FilterType = global::Soenneker.HubSpot.OpenApiClient.Models.CrmPublicInListFilter_filterType.IN_LIST;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.CrmPublicInListFilter"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HubSpot.OpenApiClient.Models.CrmPublicInListFilter CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HubSpot.OpenApiClient.Models.CrmPublicInListFilter();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "filterType", n => { FilterType = n.GetEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.CrmPublicInListFilter_filterType>(); } },
                { "listId", n => { ListId = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.CrmPublicInListFilterMetadata>(global::Soenneker.HubSpot.OpenApiClient.Models.CrmPublicInListFilterMetadata.CreateFromDiscriminatorValue); } },
                { "operator", n => { Operator = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.CrmPublicInListFilter_filterType>("filterType", FilterType);
            writer.WriteStringValue("listId", ListId);
            writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.CrmPublicInListFilterMetadata>("metadata", Metadata);
            writer.WriteStringValue("operator", Operator);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
