// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Events_Manage_Event_Definitions_DatePoint_timezoneSource
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "CUSTOM")]
        #pragma warning disable CS1591
        CUSTOM,
        #pragma warning restore CS1591
        [EnumMember(Value = "PORTAL")]
        #pragma warning disable CS1591
        PORTAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "USER")]
        #pragma warning disable CS1591
        USER,
        #pragma warning restore CS1591
    }
}
