// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Events_AssociationDefinition_hiddenReason
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "DEFAULT")]
        #pragma warning disable CS1591
        DEFAULT,
        #pragma warning restore CS1591
        [EnumMember(Value = "INTERNAL")]
        #pragma warning disable CS1591
        INTERNAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "USER_CONFIGURED")]
        #pragma warning disable CS1591
        USER_CONFIGURED,
        #pragma warning restore CS1591
    }
}
