// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    /// <summary>A string indicating the type of time representation, with a default value of &apos;DATE&apos;.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EventsDateTimeType
    {
        [EnumMember(Value = "DATE")]
        #pragma warning disable CS1591
        Date,
        #pragma warning restore CS1591
    }
}
