// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EventVisibilityChange : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The eventType property</summary>
        public global::Soenneker.HubSpot.OpenApiClient.Models.EventVisibilityChange_eventType? EventType { get; set; }
        /// <summary>The showInReporting property</summary>
        public bool? ShowInReporting { get; set; }
        /// <summary>The showInTimeline property</summary>
        public bool? ShowInTimeline { get; set; }
        /// <summary>The showInWorkflows property</summary>
        public bool? ShowInWorkflows { get; set; }
        /// <summary>The updatedAt property</summary>
        public long? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.EventVisibilityChange"/> and sets the default values.
        /// </summary>
        public EventVisibilityChange()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.EventVisibilityChange"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HubSpot.OpenApiClient.Models.EventVisibilityChange CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HubSpot.OpenApiClient.Models.EventVisibilityChange();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "eventType", n => { EventType = n.GetEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.EventVisibilityChange_eventType>(); } },
                { "showInReporting", n => { ShowInReporting = n.GetBoolValue(); } },
                { "showInTimeline", n => { ShowInTimeline = n.GetBoolValue(); } },
                { "showInWorkflows", n => { ShowInWorkflows = n.GetBoolValue(); } },
                { "updatedAt", n => { UpdatedAt = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.EventVisibilityChange_eventType>("eventType", EventType);
            writer.WriteBoolValue("showInReporting", ShowInReporting);
            writer.WriteBoolValue("showInTimeline", ShowInTimeline);
            writer.WriteBoolValue("showInWorkflows", ShowInWorkflows);
            writer.WriteLongValue("updatedAt", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
