// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ExternalMeetingsLinkSettings : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>An object representing the availability settings for the meeting link, with additional properties for closed ranges.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HubSpot.OpenApiClient.Models.ExternalMeetingsLinkSettingsAvailabilityProperty? Availability { get; set; }
#nullable restore
#else
        public global::Soenneker.HubSpot.OpenApiClient.Models.ExternalMeetingsLinkSettingsAvailabilityProperty Availability { get; set; }
#endif
        /// <summary>An integer representing the custom availability end date as a Unix timestamp in milliseconds.</summary>
        public long? CustomAvailabilityEndDate { get; set; }
        /// <summary>An integer representing the custom availability start date as a Unix timestamp in milliseconds.</summary>
        public long? CustomAvailabilityStartDate { get; set; }
        /// <summary>The displayInfo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HubSpot.OpenApiClient.Models.ExternalLinkDisplayInfo? DisplayInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.HubSpot.OpenApiClient.Models.ExternalLinkDisplayInfo DisplayInfo { get; set; }
#endif
        /// <summary>An array of integers representing the possible durations for meetings in milliseconds.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<long?>? Durations { get; set; }
#nullable restore
#else
        public List<long?> Durations { get; set; }
#endif
        /// <summary>An array of form fields that are included in the meeting link form.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.HubSpot.OpenApiClient.Models.ExternalLinkFormField>? FormFields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.HubSpot.OpenApiClient.Models.ExternalLinkFormField> FormFields { get; set; }
#endif
        /// <summary>The guestSettings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HubSpot.OpenApiClient.Models.ExternalGuestSettings? GuestSettings { get; set; }
#nullable restore
#else
        public global::Soenneker.HubSpot.OpenApiClient.Models.ExternalGuestSettings GuestSettings { get; set; }
#endif
        /// <summary>A string representing the language setting for the meeting link.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Language { get; set; }
#nullable restore
#else
        public string Language { get; set; }
#endif
        /// <summary>A boolean indicating whether legal consent is required for the meeting link.</summary>
        public bool? LegalConsentEnabled { get; set; }
        /// <summary>The legalConsentOptions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HubSpot.OpenApiClient.Models.ExternalLegalConsentOptions? LegalConsentOptions { get; set; }
#nullable restore
#else
        public global::Soenneker.HubSpot.OpenApiClient.Models.ExternalLegalConsentOptions LegalConsentOptions { get; set; }
#endif
        /// <summary>A string representing the locale setting for the meeting link.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Locale { get; set; }
#nullable restore
#else
        public string Locale { get; set; }
#endif
        /// <summary>A string representing the location information for the meeting.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Location { get; set; }
#nullable restore
#else
        public string Location { get; set; }
#endif
        /// <summary>An integer representing the buffer time between meetings in milliseconds.</summary>
        public long? MeetingBufferTime { get; set; }
        /// <summary>A boolean indicating whether the meeting owner is prioritized in scheduling.</summary>
        public bool? OwnerPrioritized { get; set; }
        /// <summary>A string representing the URL to which users are redirected after booking a meeting.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RedirectUrl { get; set; }
#nullable restore
#else
        public string RedirectUrl { get; set; }
#endif
        /// <summary>A string indicating the increment for start times, with valid values including &apos;MEETING_DURATION&apos;, &apos;FIVE&apos;, &apos;TEN&apos;, &apos;FIFTEEN&apos;, &apos;TWENTY&apos;, &apos;THIRTY&apos;, &apos;FORTY_FIVE&apos;, &apos;SIXTY&apos;, &apos;NINETY&apos;, and &apos;ONE_HUNDRED_TWENTY&apos;.</summary>
        public global::Soenneker.HubSpot.OpenApiClient.Models.ExternalMeetingsLinkSettingsStartTimeIncrementMinutes? StartTimeIncrementMinutes { get; set; }
        /// <summary>An integer representing the number of weeks to advertise the meeting link.</summary>
        public int? WeeksToAdvertise { get; set; }
        /// <summary>The welcomeScreenInfo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HubSpot.OpenApiClient.Models.ExternalMeetingsWelcomeScreenInfo? WelcomeScreenInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.HubSpot.OpenApiClient.Models.ExternalMeetingsWelcomeScreenInfo WelcomeScreenInfo { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.ExternalMeetingsLinkSettings"/> and sets the default values.
        /// </summary>
        public ExternalMeetingsLinkSettings()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.ExternalMeetingsLinkSettings"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HubSpot.OpenApiClient.Models.ExternalMeetingsLinkSettings CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HubSpot.OpenApiClient.Models.ExternalMeetingsLinkSettings();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "availability", n => { Availability = n.GetObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.ExternalMeetingsLinkSettingsAvailabilityProperty>(global::Soenneker.HubSpot.OpenApiClient.Models.ExternalMeetingsLinkSettingsAvailabilityProperty.CreateFromDiscriminatorValue); } },
                { "customAvailabilityEndDate", n => { CustomAvailabilityEndDate = n.GetLongValue(); } },
                { "customAvailabilityStartDate", n => { CustomAvailabilityStartDate = n.GetLongValue(); } },
                { "displayInfo", n => { DisplayInfo = n.GetObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.ExternalLinkDisplayInfo>(global::Soenneker.HubSpot.OpenApiClient.Models.ExternalLinkDisplayInfo.CreateFromDiscriminatorValue); } },
                { "durations", n => { Durations = n.GetCollectionOfPrimitiveValues<long?>()?.AsList(); } },
                { "formFields", n => { FormFields = n.GetCollectionOfObjectValues<global::Soenneker.HubSpot.OpenApiClient.Models.ExternalLinkFormField>(global::Soenneker.HubSpot.OpenApiClient.Models.ExternalLinkFormField.CreateFromDiscriminatorValue)?.AsList(); } },
                { "guestSettings", n => { GuestSettings = n.GetObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.ExternalGuestSettings>(global::Soenneker.HubSpot.OpenApiClient.Models.ExternalGuestSettings.CreateFromDiscriminatorValue); } },
                { "language", n => { Language = n.GetStringValue(); } },
                { "legalConsentEnabled", n => { LegalConsentEnabled = n.GetBoolValue(); } },
                { "legalConsentOptions", n => { LegalConsentOptions = n.GetObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.ExternalLegalConsentOptions>(global::Soenneker.HubSpot.OpenApiClient.Models.ExternalLegalConsentOptions.CreateFromDiscriminatorValue); } },
                { "locale", n => { Locale = n.GetStringValue(); } },
                { "location", n => { Location = n.GetStringValue(); } },
                { "meetingBufferTime", n => { MeetingBufferTime = n.GetLongValue(); } },
                { "ownerPrioritized", n => { OwnerPrioritized = n.GetBoolValue(); } },
                { "redirectUrl", n => { RedirectUrl = n.GetStringValue(); } },
                { "startTimeIncrementMinutes", n => { StartTimeIncrementMinutes = n.GetEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.ExternalMeetingsLinkSettingsStartTimeIncrementMinutes>(); } },
                { "weeksToAdvertise", n => { WeeksToAdvertise = n.GetIntValue(); } },
                { "welcomeScreenInfo", n => { WelcomeScreenInfo = n.GetObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.ExternalMeetingsWelcomeScreenInfo>(global::Soenneker.HubSpot.OpenApiClient.Models.ExternalMeetingsWelcomeScreenInfo.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.ExternalMeetingsLinkSettingsAvailabilityProperty>("availability", Availability);
            writer.WriteLongValue("customAvailabilityEndDate", CustomAvailabilityEndDate);
            writer.WriteLongValue("customAvailabilityStartDate", CustomAvailabilityStartDate);
            writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.ExternalLinkDisplayInfo>("displayInfo", DisplayInfo);
            writer.WriteCollectionOfPrimitiveValues<long?>("durations", Durations);
            writer.WriteCollectionOfObjectValues<global::Soenneker.HubSpot.OpenApiClient.Models.ExternalLinkFormField>("formFields", FormFields);
            writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.ExternalGuestSettings>("guestSettings", GuestSettings);
            writer.WriteStringValue("language", Language);
            writer.WriteBoolValue("legalConsentEnabled", LegalConsentEnabled);
            writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.ExternalLegalConsentOptions>("legalConsentOptions", LegalConsentOptions);
            writer.WriteStringValue("locale", Locale);
            writer.WriteStringValue("location", Location);
            writer.WriteLongValue("meetingBufferTime", MeetingBufferTime);
            writer.WriteBoolValue("ownerPrioritized", OwnerPrioritized);
            writer.WriteStringValue("redirectUrl", RedirectUrl);
            writer.WriteEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.ExternalMeetingsLinkSettingsStartTimeIncrementMinutes>("startTimeIncrementMinutes", StartTimeIncrementMinutes);
            writer.WriteIntValue("weeksToAdvertise", WeeksToAdvertise);
            writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.ExternalMeetingsWelcomeScreenInfo>("welcomeScreenInfo", WelcomeScreenInfo);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
