// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    /// <summary>A string indicating the avatar display option, with valid values including &apos;PROFILE_IMAGE&apos;, &apos;COMPANY_LOGO&apos;, and &apos;CUSTOM_AVATAR&apos;.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ExternalLinkDisplayInfoPublicDisplayAvatarOption
    {
        [EnumMember(Value = "COMPANY_LOGO")]
        #pragma warning disable CS1591
        CompanyLogo,
        #pragma warning restore CS1591
        [EnumMember(Value = "CUSTOM_AVATAR")]
        #pragma warning disable CS1591
        CustomAvatar,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROFILE_IMAGE")]
        #pragma warning disable CS1591
        ProfileImage,
        #pragma warning restore CS1591
    }
}
