// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    /// <summary>&quot;The type of the meeting link. Accepted values are: GROUP_CALENDAR, PERSONAL_LINK, ROUND_ROBIN_CALENDAR.&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ExternalBookingInfoLinkType
    {
        [EnumMember(Value = "GROUP_CALENDAR")]
        #pragma warning disable CS1591
        GroupCalendar,
        #pragma warning restore CS1591
        [EnumMember(Value = "PERSONAL_LINK")]
        #pragma warning disable CS1591
        PersonalLink,
        #pragma warning restore CS1591
        [EnumMember(Value = "ROUND_ROBIN_CALENDAR")]
        #pragma warning disable CS1591
        RoundRobinCalendar,
        #pragma warning restore CS1591
    }
}
