// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    /// <summary>The type of the fee value, indicating whether it is a fixed amount or a percentage. Valid values include &apos;FIXED&apos; and &apos;PERCENT&apos;.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FeeRequestValueType
    {
        [EnumMember(Value = "FIXED")]
        #pragma warning disable CS1591
        FixedValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "PERCENT")]
        #pragma warning disable CS1591
        Percent,
        #pragma warning restore CS1591
    }
}
