// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    /// <summary>The flag state for any portal that doesn&apos;t have an override value</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FlagResponse_defaultState
    {
        [EnumMember(Value = "ABSENT")]
        #pragma warning disable CS1591
        ABSENT,
        #pragma warning restore CS1591
        [EnumMember(Value = "OFF")]
        #pragma warning disable CS1591
        OFF,
        #pragma warning restore CS1591
        [EnumMember(Value = "ON")]
        #pragma warning disable CS1591
        ON,
        #pragma warning restore CS1591
    }
}
