// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    /// <summary>The classification of what type of template this represents, and what is its origin or purpose.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ImportTemplateTemplateType
    {
        [EnumMember(Value = "admin_defined")]
        #pragma warning disable CS1591
        AdminDefined,
        #pragma warning restore CS1591
        [EnumMember(Value = "previous_import")]
        #pragma warning disable CS1591
        PreviousImport,
        #pragma warning restore CS1591
        [EnumMember(Value = "user_file")]
        #pragma warning disable CS1591
        UserFile,
        #pragma warning restore CS1591
    }
}
