// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    /// <summary>Indicates the type of filter being applied (IN_LIST).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum InListFilterType
    {
        [EnumMember(Value = "IN_LIST")]
        #pragma warning disable CS1591
        InList,
        #pragma warning restore CS1591
    }
}
