// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    /// <summary>The type of delay for the start of billing. Valid values include &apos;HS_BILLING_START_DELAY_DAYS&apos;, &apos;HS_BILLING_START_DELAY_MONTHS&apos;, and &apos;HS_RECURRING_BILLING_START_DATE&apos;.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum LineItemBillingStartDelayType
    {
        [EnumMember(Value = "HS_BILLING_START_DELAY_DAYS")]
        #pragma warning disable CS1591
        HsBillingStartDelayDays,
        #pragma warning restore CS1591
        [EnumMember(Value = "HS_BILLING_START_DELAY_MONTHS")]
        #pragma warning disable CS1591
        HsBillingStartDelayMonths,
        #pragma warning restore CS1591
        [EnumMember(Value = "HS_RECURRING_BILLING_START_DATE")]
        #pragma warning disable CS1591
        HsRecurringBillingStartDate,
        #pragma warning restore CS1591
    }
}
