// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    /// <summary>
    /// An input used to update some properties on a pipeline definition.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PipelineStagePatchInput : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether the pipeline is archived.</summary>
        public bool? Archived { get; set; }
        /// <summary>The order for displaying this pipeline stage. If two pipeline stages have a matching `displayOrder`, they will be sorted alphabetically by label.</summary>
        public int? DisplayOrder { get; set; }
        /// <summary>A label used to organize pipeline stages in HubSpot&apos;s UI. Each pipeline stage&apos;s label must be unique within that pipeline.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Label { get; set; }
#nullable restore
#else
        public string Label { get; set; }
#endif
        /// <summary>&quot;A JSON object containing properties that are not present on all object pipelines.For `deals` pipelines, the `probability` field is required (`{ \&quot;probability\&quot;: 0.5 }`), and represents the likelihood a deal will close. Possible values are between 0.0 and 1.0 in increments of 0.1.For `tickets` pipelines, the `ticketState` field is optional (`{ \&quot;ticketState\&quot;: \&quot;OPEN\&quot; }`), and represents whether the ticket remains open or has been closed by a member of your Support team. Possible values are `OPEN` or `CLOSED`.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HubSpot.OpenApiClient.Models.PipelineStagePatchInput_metadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.HubSpot.OpenApiClient.Models.PipelineStagePatchInput_metadata Metadata { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PipelineStagePatchInput"/> and sets the default values.
        /// </summary>
        public PipelineStagePatchInput()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PipelineStagePatchInput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HubSpot.OpenApiClient.Models.PipelineStagePatchInput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HubSpot.OpenApiClient.Models.PipelineStagePatchInput();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "archived", n => { Archived = n.GetBoolValue(); } },
                { "displayOrder", n => { DisplayOrder = n.GetIntValue(); } },
                { "label", n => { Label = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.PipelineStagePatchInput_metadata>(global::Soenneker.HubSpot.OpenApiClient.Models.PipelineStagePatchInput_metadata.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("archived", Archived);
            writer.WriteIntValue("displayOrder", DisplayOrder);
            writer.WriteStringValue("label", Label);
            writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.PipelineStagePatchInput_metadata>("metadata", Metadata);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
