// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PreResolvedContact_contactPropertiesLeadingToMatch
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "address")]
        #pragma warning disable CS1591
        Address,
        #pragma warning restore CS1591
        [EnumMember(Value = "annualrevenue")]
        #pragma warning disable CS1591
        Annualrevenue,
        #pragma warning restore CS1591
        [EnumMember(Value = "associatedcompanyid")]
        #pragma warning disable CS1591
        Associatedcompanyid,
        #pragma warning restore CS1591
        [EnumMember(Value = "associatedcompanylastupdated")]
        #pragma warning disable CS1591
        Associatedcompanylastupdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "city")]
        #pragma warning disable CS1591
        City,
        #pragma warning restore CS1591
        [EnumMember(Value = "closedate")]
        #pragma warning disable CS1591
        Closedate,
        #pragma warning restore CS1591
        [EnumMember(Value = "company")]
        #pragma warning disable CS1591
        Company,
        #pragma warning restore CS1591
        [EnumMember(Value = "company_size")]
        #pragma warning disable CS1591
        Company_size,
        #pragma warning restore CS1591
        [EnumMember(Value = "country")]
        #pragma warning disable CS1591
        Country,
        #pragma warning restore CS1591
        [EnumMember(Value = "createdate")]
        #pragma warning disable CS1591
        Createdate,
        #pragma warning restore CS1591
        [EnumMember(Value = "currentlyinworkflow")]
        #pragma warning disable CS1591
        Currentlyinworkflow,
        #pragma warning restore CS1591
        [EnumMember(Value = "date_of_birth")]
        #pragma warning disable CS1591
        Date_of_birth,
        #pragma warning restore CS1591
        [EnumMember(Value = "days_to_close")]
        #pragma warning disable CS1591
        Days_to_close,
        #pragma warning restore CS1591
        [EnumMember(Value = "degree")]
        #pragma warning disable CS1591
        Degree,
        #pragma warning restore CS1591
        [EnumMember(Value = "email")]
        #pragma warning disable CS1591
        Email,
        #pragma warning restore CS1591
        [EnumMember(Value = "engagements_last_meeting_booked")]
        #pragma warning disable CS1591
        Engagements_last_meeting_booked,
        #pragma warning restore CS1591
        [EnumMember(Value = "engagements_last_meeting_booked_campaign")]
        #pragma warning disable CS1591
        Engagements_last_meeting_booked_campaign,
        #pragma warning restore CS1591
        [EnumMember(Value = "engagements_last_meeting_booked_medium")]
        #pragma warning disable CS1591
        Engagements_last_meeting_booked_medium,
        #pragma warning restore CS1591
        [EnumMember(Value = "engagements_last_meeting_booked_source")]
        #pragma warning disable CS1591
        Engagements_last_meeting_booked_source,
        #pragma warning restore CS1591
        [EnumMember(Value = "fax")]
        #pragma warning disable CS1591
        Fax,
        #pragma warning restore CS1591
        [EnumMember(Value = "field_of_study")]
        #pragma warning disable CS1591
        Field_of_study,
        #pragma warning restore CS1591
        [EnumMember(Value = "first_conversion_date")]
        #pragma warning disable CS1591
        First_conversion_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "first_conversion_event_name")]
        #pragma warning disable CS1591
        First_conversion_event_name,
        #pragma warning restore CS1591
        [EnumMember(Value = "first_deal_created_date")]
        #pragma warning disable CS1591
        First_deal_created_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "firstname")]
        #pragma warning disable CS1591
        Firstname,
        #pragma warning restore CS1591
        [EnumMember(Value = "followercount")]
        #pragma warning disable CS1591
        Followercount,
        #pragma warning restore CS1591
        [EnumMember(Value = "gender")]
        #pragma warning disable CS1591
        Gender,
        #pragma warning restore CS1591
        [EnumMember(Value = "graduation_date")]
        #pragma warning disable CS1591
        Graduation_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_additional_emails")]
        #pragma warning disable CS1591
        Hs_additional_emails,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_all_contact_vids")]
        #pragma warning disable CS1591
        Hs_all_contact_vids,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_analytics_average_page_views")]
        #pragma warning disable CS1591
        Hs_analytics_average_page_views,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_analytics_first_referrer")]
        #pragma warning disable CS1591
        Hs_analytics_first_referrer,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_analytics_first_timestamp")]
        #pragma warning disable CS1591
        Hs_analytics_first_timestamp,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_analytics_first_touch_converting_campaign")]
        #pragma warning disable CS1591
        Hs_analytics_first_touch_converting_campaign,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_analytics_first_url")]
        #pragma warning disable CS1591
        Hs_analytics_first_url,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_analytics_first_visit_timestamp")]
        #pragma warning disable CS1591
        Hs_analytics_first_visit_timestamp,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_analytics_last_referrer")]
        #pragma warning disable CS1591
        Hs_analytics_last_referrer,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_analytics_last_timestamp")]
        #pragma warning disable CS1591
        Hs_analytics_last_timestamp,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_analytics_last_touch_converting_campaign")]
        #pragma warning disable CS1591
        Hs_analytics_last_touch_converting_campaign,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_analytics_last_url")]
        #pragma warning disable CS1591
        Hs_analytics_last_url,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_analytics_last_visit_timestamp")]
        #pragma warning disable CS1591
        Hs_analytics_last_visit_timestamp,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_analytics_num_event_completions")]
        #pragma warning disable CS1591
        Hs_analytics_num_event_completions,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_analytics_num_page_views")]
        #pragma warning disable CS1591
        Hs_analytics_num_page_views,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_analytics_num_visits")]
        #pragma warning disable CS1591
        Hs_analytics_num_visits,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_analytics_revenue")]
        #pragma warning disable CS1591
        Hs_analytics_revenue,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_analytics_source")]
        #pragma warning disable CS1591
        Hs_analytics_source,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_analytics_source_composite_data")]
        #pragma warning disable CS1591
        Hs_analytics_source_composite_data,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_analytics_source_data_1")]
        #pragma warning disable CS1591
        Hs_analytics_source_data_1,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_analytics_source_data_2")]
        #pragma warning disable CS1591
        Hs_analytics_source_data_2,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_associated_target_accounts")]
        #pragma warning disable CS1591
        Hs_associated_target_accounts,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_avatar_filemanager_key")]
        #pragma warning disable CS1591
        Hs_avatar_filemanager_key,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_bing_ad_clicked")]
        #pragma warning disable CS1591
        Hs_bing_ad_clicked,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_bing_click_id")]
        #pragma warning disable CS1591
        Hs_bing_click_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_buying_role")]
        #pragma warning disable CS1591
        Hs_buying_role,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_calculated_form_submissions")]
        #pragma warning disable CS1591
        Hs_calculated_form_submissions,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_calculated_merged_vids")]
        #pragma warning disable CS1591
        Hs_calculated_merged_vids,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_calculated_mobile_number")]
        #pragma warning disable CS1591
        Hs_calculated_mobile_number,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_calculated_phone_number")]
        #pragma warning disable CS1591
        Hs_calculated_phone_number,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_calculated_phone_number_area_code")]
        #pragma warning disable CS1591
        Hs_calculated_phone_number_area_code,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_calculated_phone_number_country_code")]
        #pragma warning disable CS1591
        Hs_calculated_phone_number_country_code,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_calculated_phone_number_region_code")]
        #pragma warning disable CS1591
        Hs_calculated_phone_number_region_code,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_chat_assistant_iql_date")]
        #pragma warning disable CS1591
        Hs_chat_assistant_iql_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_chat_assistant_source")]
        #pragma warning disable CS1591
        Hs_chat_assistant_source,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_chat_assistant_summary")]
        #pragma warning disable CS1591
        Hs_chat_assistant_summary,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_clicked_linkedin_ad")]
        #pragma warning disable CS1591
        Hs_clicked_linkedin_ad,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_contact_creation_legal_basis_source_instance_id")]
        #pragma warning disable CS1591
        Hs_contact_creation_legal_basis_source_instance_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_contact_enrichment_opt_out")]
        #pragma warning disable CS1591
        Hs_contact_enrichment_opt_out,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_contact_enrichment_opt_out_timestamp")]
        #pragma warning disable CS1591
        Hs_contact_enrichment_opt_out_timestamp,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_content_membership_email")]
        #pragma warning disable CS1591
        Hs_content_membership_email,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_content_membership_email_confirmed")]
        #pragma warning disable CS1591
        Hs_content_membership_email_confirmed,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_content_membership_follow_up_enqueued_at")]
        #pragma warning disable CS1591
        Hs_content_membership_follow_up_enqueued_at,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_content_membership_notes")]
        #pragma warning disable CS1591
        Hs_content_membership_notes,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_content_membership_registered_at")]
        #pragma warning disable CS1591
        Hs_content_membership_registered_at,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_content_membership_registration_domain_sent_to")]
        #pragma warning disable CS1591
        Hs_content_membership_registration_domain_sent_to,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_content_membership_registration_email_sent_at")]
        #pragma warning disable CS1591
        Hs_content_membership_registration_email_sent_at,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_content_membership_status")]
        #pragma warning disable CS1591
        Hs_content_membership_status,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_conversations_visitor_email")]
        #pragma warning disable CS1591
        Hs_conversations_visitor_email,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_count_is_unworked")]
        #pragma warning disable CS1591
        Hs_count_is_unworked,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_count_is_worked")]
        #pragma warning disable CS1591
        Hs_count_is_worked,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_country_region_code")]
        #pragma warning disable CS1591
        Hs_country_region_code,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_created_by_conversations")]
        #pragma warning disable CS1591
        Hs_created_by_conversations,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_cross_account_note")]
        #pragma warning disable CS1591
        Hs_cross_account_note,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_cross_sell_opportunity")]
        #pragma warning disable CS1591
        Hs_cross_sell_opportunity,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_current_customer")]
        #pragma warning disable CS1591
        Hs_current_customer,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_currently_enrolled_in_prospecting_agent")]
        #pragma warning disable CS1591
        Hs_currently_enrolled_in_prospecting_agent,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_customer_agent_lead_status")]
        #pragma warning disable CS1591
        Hs_customer_agent_lead_status,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_data_privacy_ads_consent")]
        #pragma warning disable CS1591
        Hs_data_privacy_ads_consent,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_date_entered_customer")]
        #pragma warning disable CS1591
        Hs_date_entered_customer,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_date_entered_evangelist")]
        #pragma warning disable CS1591
        Hs_date_entered_evangelist,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_date_entered_lead")]
        #pragma warning disable CS1591
        Hs_date_entered_lead,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_date_entered_marketingqualifiedlead")]
        #pragma warning disable CS1591
        Hs_date_entered_marketingqualifiedlead,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_date_entered_opportunity")]
        #pragma warning disable CS1591
        Hs_date_entered_opportunity,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_date_entered_other")]
        #pragma warning disable CS1591
        Hs_date_entered_other,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_date_entered_salesqualifiedlead")]
        #pragma warning disable CS1591
        Hs_date_entered_salesqualifiedlead,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_date_entered_subscriber")]
        #pragma warning disable CS1591
        Hs_date_entered_subscriber,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_date_exited_customer")]
        #pragma warning disable CS1591
        Hs_date_exited_customer,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_date_exited_evangelist")]
        #pragma warning disable CS1591
        Hs_date_exited_evangelist,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_date_exited_lead")]
        #pragma warning disable CS1591
        Hs_date_exited_lead,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_date_exited_marketingqualifiedlead")]
        #pragma warning disable CS1591
        Hs_date_exited_marketingqualifiedlead,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_date_exited_opportunity")]
        #pragma warning disable CS1591
        Hs_date_exited_opportunity,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_date_exited_other")]
        #pragma warning disable CS1591
        Hs_date_exited_other,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_date_exited_salesqualifiedlead")]
        #pragma warning disable CS1591
        Hs_date_exited_salesqualifiedlead,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_date_exited_subscriber")]
        #pragma warning disable CS1591
        Hs_date_exited_subscriber,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_document_last_revisited")]
        #pragma warning disable CS1591
        Hs_document_last_revisited,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_email_bad_address")]
        #pragma warning disable CS1591
        Hs_email_bad_address,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_email_bounce")]
        #pragma warning disable CS1591
        Hs_email_bounce,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_email_click")]
        #pragma warning disable CS1591
        Hs_email_click,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_email_customer_quarantined_reason")]
        #pragma warning disable CS1591
        Hs_email_customer_quarantined_reason,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_email_delivered")]
        #pragma warning disable CS1591
        Hs_email_delivered,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_email_domain")]
        #pragma warning disable CS1591
        Hs_email_domain,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_email_first_click_date")]
        #pragma warning disable CS1591
        Hs_email_first_click_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_email_first_open_date")]
        #pragma warning disable CS1591
        Hs_email_first_open_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_email_first_reply_date")]
        #pragma warning disable CS1591
        Hs_email_first_reply_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_email_first_send_date")]
        #pragma warning disable CS1591
        Hs_email_first_send_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_email_hard_bounce_reason")]
        #pragma warning disable CS1591
        Hs_email_hard_bounce_reason,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_email_hard_bounce_reason_enum")]
        #pragma warning disable CS1591
        Hs_email_hard_bounce_reason_enum,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_email_is_ineligible")]
        #pragma warning disable CS1591
        Hs_email_is_ineligible,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_email_last_click_date")]
        #pragma warning disable CS1591
        Hs_email_last_click_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_email_last_email_name")]
        #pragma warning disable CS1591
        Hs_email_last_email_name,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_email_last_open_date")]
        #pragma warning disable CS1591
        Hs_email_last_open_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_email_last_reply_date")]
        #pragma warning disable CS1591
        Hs_email_last_reply_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_email_last_send_date")]
        #pragma warning disable CS1591
        Hs_email_last_send_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_email_live_sourcing_restricted")]
        #pragma warning disable CS1591
        Hs_email_live_sourcing_restricted,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_email_open")]
        #pragma warning disable CS1591
        Hs_email_open,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_email_optimal_send_day_of_week")]
        #pragma warning disable CS1591
        Hs_email_optimal_send_day_of_week,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_email_optimal_send_time_of_day")]
        #pragma warning disable CS1591
        Hs_email_optimal_send_time_of_day,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_email_optout")]
        #pragma warning disable CS1591
        Hs_email_optout,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_email_optout_survey_reason")]
        #pragma warning disable CS1591
        Hs_email_optout_survey_reason,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_email_quarantined")]
        #pragma warning disable CS1591
        Hs_email_quarantined,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_email_quarantined_reason")]
        #pragma warning disable CS1591
        Hs_email_quarantined_reason,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_email_recipient_fatigue_recovery_time")]
        #pragma warning disable CS1591
        Hs_email_recipient_fatigue_recovery_time,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_email_replied")]
        #pragma warning disable CS1591
        Hs_email_replied,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_email_sends_since_last_engagement")]
        #pragma warning disable CS1591
        Hs_email_sends_since_last_engagement,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_email_type")]
        #pragma warning disable CS1591
        Hs_email_type,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_emailconfirmationstatus")]
        #pragma warning disable CS1591
        Hs_emailconfirmationstatus,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_employment_change_detected_date")]
        #pragma warning disable CS1591
        Hs_employment_change_detected_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_enriched_email_bounce_detected")]
        #pragma warning disable CS1591
        Hs_enriched_email_bounce_detected,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_excluded_from_cross_account_data_mirroring")]
        #pragma warning disable CS1591
        Hs_excluded_from_cross_account_data_mirroring,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_facebook_ad_clicked")]
        #pragma warning disable CS1591
        Hs_facebook_ad_clicked,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_facebook_click_id")]
        #pragma warning disable CS1591
        Hs_facebook_click_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_facebookid")]
        #pragma warning disable CS1591
        Hs_facebookid,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_feedback_last_ces_survey_date")]
        #pragma warning disable CS1591
        Hs_feedback_last_ces_survey_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_feedback_last_ces_survey_follow_up")]
        #pragma warning disable CS1591
        Hs_feedback_last_ces_survey_follow_up,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_feedback_last_ces_survey_rating")]
        #pragma warning disable CS1591
        Hs_feedback_last_ces_survey_rating,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_feedback_last_csat_survey_date")]
        #pragma warning disable CS1591
        Hs_feedback_last_csat_survey_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_feedback_last_csat_survey_follow_up")]
        #pragma warning disable CS1591
        Hs_feedback_last_csat_survey_follow_up,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_feedback_last_csat_survey_rating")]
        #pragma warning disable CS1591
        Hs_feedback_last_csat_survey_rating,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_feedback_last_nps_follow_up")]
        #pragma warning disable CS1591
        Hs_feedback_last_nps_follow_up,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_feedback_last_nps_rating")]
        #pragma warning disable CS1591
        Hs_feedback_last_nps_rating,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_feedback_last_nps_rating_number")]
        #pragma warning disable CS1591
        Hs_feedback_last_nps_rating_number,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_feedback_last_survey_date")]
        #pragma warning disable CS1591
        Hs_feedback_last_survey_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_feedback_show_nps_web_survey")]
        #pragma warning disable CS1591
        Hs_feedback_show_nps_web_survey,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_first_closed_order_id")]
        #pragma warning disable CS1591
        Hs_first_closed_order_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_first_engagement_object_id")]
        #pragma warning disable CS1591
        Hs_first_engagement_object_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_first_order_closed_date")]
        #pragma warning disable CS1591
        Hs_first_order_closed_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_first_outreach_date")]
        #pragma warning disable CS1591
        Hs_first_outreach_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_first_subscription_create_date")]
        #pragma warning disable CS1591
        Hs_first_subscription_create_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_full_name_or_email")]
        #pragma warning disable CS1591
        Hs_full_name_or_email,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_google_click_id")]
        #pragma warning disable CS1591
        Hs_google_click_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_googleplusid")]
        #pragma warning disable CS1591
        Hs_googleplusid,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_gps_coordinates")]
        #pragma warning disable CS1591
        Hs_gps_coordinates,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_gps_error")]
        #pragma warning disable CS1591
        Hs_gps_error,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_gps_latitude")]
        #pragma warning disable CS1591
        Hs_gps_latitude,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_gps_longitude")]
        #pragma warning disable CS1591
        Hs_gps_longitude,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_has_active_subscription")]
        #pragma warning disable CS1591
        Hs_has_active_subscription,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_inferred_language_codes")]
        #pragma warning disable CS1591
        Hs_inferred_language_codes,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_intent_paid_up_to_date")]
        #pragma warning disable CS1591
        Hs_intent_paid_up_to_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_intent_signals_enabled")]
        #pragma warning disable CS1591
        Hs_intent_signals_enabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_ip_timezone")]
        #pragma warning disable CS1591
        Hs_ip_timezone,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_is_contact")]
        #pragma warning disable CS1591
        Hs_is_contact,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_is_enriched")]
        #pragma warning disable CS1591
        Hs_is_enriched,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_is_merge_revertible")]
        #pragma warning disable CS1591
        Hs_is_merge_revertible,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_is_unworked")]
        #pragma warning disable CS1591
        Hs_is_unworked,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_job_change_detected_date")]
        #pragma warning disable CS1591
        Hs_job_change_detected_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_journey_stage")]
        #pragma warning disable CS1591
        Hs_journey_stage,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_language")]
        #pragma warning disable CS1591
        Hs_language,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_last_metered_enrichment_timestamp")]
        #pragma warning disable CS1591
        Hs_last_metered_enrichment_timestamp,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_last_sales_activity_date")]
        #pragma warning disable CS1591
        Hs_last_sales_activity_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_last_sales_activity_timestamp")]
        #pragma warning disable CS1591
        Hs_last_sales_activity_timestamp,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_last_sales_activity_type")]
        #pragma warning disable CS1591
        Hs_last_sales_activity_type,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_last_sms_send_date")]
        #pragma warning disable CS1591
        Hs_last_sms_send_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_last_sms_send_name")]
        #pragma warning disable CS1591
        Hs_last_sms_send_name,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_latest_disqualified_lead_date")]
        #pragma warning disable CS1591
        Hs_latest_disqualified_lead_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_latest_meeting_activity")]
        #pragma warning disable CS1591
        Hs_latest_meeting_activity,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_latest_open_lead_date")]
        #pragma warning disable CS1591
        Hs_latest_open_lead_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_latest_qualified_lead_date")]
        #pragma warning disable CS1591
        Hs_latest_qualified_lead_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_latest_sequence_ended_date")]
        #pragma warning disable CS1591
        Hs_latest_sequence_ended_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_latest_sequence_enrolled")]
        #pragma warning disable CS1591
        Hs_latest_sequence_enrolled,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_latest_sequence_enrolled_date")]
        #pragma warning disable CS1591
        Hs_latest_sequence_enrolled_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_latest_sequence_finished_date")]
        #pragma warning disable CS1591
        Hs_latest_sequence_finished_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_latest_sequence_unenrolled_date")]
        #pragma warning disable CS1591
        Hs_latest_sequence_unenrolled_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_latest_source")]
        #pragma warning disable CS1591
        Hs_latest_source,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_latest_source_composite_data")]
        #pragma warning disable CS1591
        Hs_latest_source_composite_data,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_latest_source_data_1")]
        #pragma warning disable CS1591
        Hs_latest_source_data_1,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_latest_source_data_2")]
        #pragma warning disable CS1591
        Hs_latest_source_data_2,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_latest_source_timestamp")]
        #pragma warning disable CS1591
        Hs_latest_source_timestamp,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_latest_subscription_create_date")]
        #pragma warning disable CS1591
        Hs_latest_subscription_create_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_latitude")]
        #pragma warning disable CS1591
        Hs_latitude,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_lead_status")]
        #pragma warning disable CS1591
        Hs_lead_status,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_legal_basis")]
        #pragma warning disable CS1591
        Hs_legal_basis,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_lifecyclestage_customer_date")]
        #pragma warning disable CS1591
        Hs_lifecyclestage_customer_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_lifecyclestage_evangelist_date")]
        #pragma warning disable CS1591
        Hs_lifecyclestage_evangelist_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_lifecyclestage_lead_date")]
        #pragma warning disable CS1591
        Hs_lifecyclestage_lead_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_lifecyclestage_marketingqualifiedlead_date")]
        #pragma warning disable CS1591
        Hs_lifecyclestage_marketingqualifiedlead_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_lifecyclestage_opportunity_date")]
        #pragma warning disable CS1591
        Hs_lifecyclestage_opportunity_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_lifecyclestage_other_date")]
        #pragma warning disable CS1591
        Hs_lifecyclestage_other_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_lifecyclestage_salesqualifiedlead_date")]
        #pragma warning disable CS1591
        Hs_lifecyclestage_salesqualifiedlead_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_lifecyclestage_subscriber_date")]
        #pragma warning disable CS1591
        Hs_lifecyclestage_subscriber_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_linkedin_ad_clicked")]
        #pragma warning disable CS1591
        Hs_linkedin_ad_clicked,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_linkedin_click_id")]
        #pragma warning disable CS1591
        Hs_linkedin_click_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_linkedin_url")]
        #pragma warning disable CS1591
        Hs_linkedin_url,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_linkedinid")]
        #pragma warning disable CS1591
        Hs_linkedinid,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_live_enrichment_deadline")]
        #pragma warning disable CS1591
        Hs_live_enrichment_deadline,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_longitude")]
        #pragma warning disable CS1591
        Hs_longitude,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_manual_campaign_ids")]
        #pragma warning disable CS1591
        Hs_manual_campaign_ids,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_marketable_reason_id")]
        #pragma warning disable CS1591
        Hs_marketable_reason_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_marketable_reason_type")]
        #pragma warning disable CS1591
        Hs_marketable_reason_type,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_marketable_status")]
        #pragma warning disable CS1591
        Hs_marketable_status,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_marketable_until_renewal")]
        #pragma warning disable CS1591
        Hs_marketable_until_renewal,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_membership_has_accessed_private_content")]
        #pragma warning disable CS1591
        Hs_membership_has_accessed_private_content,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_membership_last_private_content_access_date")]
        #pragma warning disable CS1591
        Hs_membership_last_private_content_access_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_messaging_engagement_score")]
        #pragma warning disable CS1591
        Hs_messaging_engagement_score,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_mobile_sdk_push_tokens")]
        #pragma warning disable CS1591
        Hs_mobile_sdk_push_tokens,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_notes_last_activity")]
        #pragma warning disable CS1591
        Hs_notes_last_activity,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_notes_next_activity")]
        #pragma warning disable CS1591
        Hs_notes_next_activity,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_notes_next_activity_type")]
        #pragma warning disable CS1591
        Hs_notes_next_activity_type,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_persona")]
        #pragma warning disable CS1591
        Hs_persona,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_pinned_engagement_id")]
        #pragma warning disable CS1591
        Hs_pinned_engagement_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_pipeline")]
        #pragma warning disable CS1591
        Hs_pipeline,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_predictivecontactscore")]
        #pragma warning disable CS1591
        Hs_predictivecontactscore,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_predictivecontactscore_tmp")]
        #pragma warning disable CS1591
        Hs_predictivecontactscore_tmp,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_predictivecontactscore_v2")]
        #pragma warning disable CS1591
        Hs_predictivecontactscore_v2,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_predictivecontactscorebucket")]
        #pragma warning disable CS1591
        Hs_predictivecontactscorebucket,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_predictivescoringtier")]
        #pragma warning disable CS1591
        Hs_predictivescoringtier,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_predictivescoringtier_tmp")]
        #pragma warning disable CS1591
        Hs_predictivescoringtier_tmp,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_prospecting_agent_actively_enrolled_count")]
        #pragma warning disable CS1591
        Hs_prospecting_agent_actively_enrolled_count,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_prospecting_agent_last_enrolled")]
        #pragma warning disable CS1591
        Hs_prospecting_agent_last_enrolled,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_prospecting_agent_total_enrolled_count")]
        #pragma warning disable CS1591
        Hs_prospecting_agent_total_enrolled_count,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_quarantined_emails")]
        #pragma warning disable CS1591
        Hs_quarantined_emails,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_recent_closed_order_date")]
        #pragma warning disable CS1591
        Hs_recent_closed_order_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_registered_member")]
        #pragma warning disable CS1591
        Hs_registered_member,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_registration_method")]
        #pragma warning disable CS1591
        Hs_registration_method,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_returning_to_office_detected_date")]
        #pragma warning disable CS1591
        Hs_returning_to_office_detected_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_role")]
        #pragma warning disable CS1591
        Hs_role,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_sa_first_engagement_date")]
        #pragma warning disable CS1591
        Hs_sa_first_engagement_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_sa_first_engagement_descr")]
        #pragma warning disable CS1591
        Hs_sa_first_engagement_descr,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_sa_first_engagement_object_type")]
        #pragma warning disable CS1591
        Hs_sa_first_engagement_object_type,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_sales_email_last_clicked")]
        #pragma warning disable CS1591
        Hs_sales_email_last_clicked,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_sales_email_last_opened")]
        #pragma warning disable CS1591
        Hs_sales_email_last_opened,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_sales_email_last_replied")]
        #pragma warning disable CS1591
        Hs_sales_email_last_replied,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_searchable_calculated_international_mobile_number")]
        #pragma warning disable CS1591
        Hs_searchable_calculated_international_mobile_number,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_searchable_calculated_international_phone_number")]
        #pragma warning disable CS1591
        Hs_searchable_calculated_international_phone_number,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_searchable_calculated_mobile_number")]
        #pragma warning disable CS1591
        Hs_searchable_calculated_mobile_number,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_searchable_calculated_phone_number")]
        #pragma warning disable CS1591
        Hs_searchable_calculated_phone_number,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_seniority")]
        #pragma warning disable CS1591
        Hs_seniority,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_sequences_actively_enrolled_count")]
        #pragma warning disable CS1591
        Hs_sequences_actively_enrolled_count,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_sequences_enrolled_count")]
        #pragma warning disable CS1591
        Hs_sequences_enrolled_count,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_sequences_is_enrolled")]
        #pragma warning disable CS1591
        Hs_sequences_is_enrolled,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_social_facebook_clicks")]
        #pragma warning disable CS1591
        Hs_social_facebook_clicks,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_social_google_plus_clicks")]
        #pragma warning disable CS1591
        Hs_social_google_plus_clicks,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_social_last_engagement")]
        #pragma warning disable CS1591
        Hs_social_last_engagement,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_social_linkedin_clicks")]
        #pragma warning disable CS1591
        Hs_social_linkedin_clicks,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_social_num_broadcast_clicks")]
        #pragma warning disable CS1591
        Hs_social_num_broadcast_clicks,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_social_twitter_clicks")]
        #pragma warning disable CS1591
        Hs_social_twitter_clicks,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_source_object_id")]
        #pragma warning disable CS1591
        Hs_source_object_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_source_portal_id")]
        #pragma warning disable CS1591
        Hs_source_portal_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_state_code")]
        #pragma warning disable CS1591
        Hs_state_code,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_sub_role")]
        #pragma warning disable CS1591
        Hs_sub_role,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_testpurge")]
        #pragma warning disable CS1591
        Hs_testpurge,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_testrollback")]
        #pragma warning disable CS1591
        Hs_testrollback,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_tiktok_ad_clicked")]
        #pragma warning disable CS1591
        Hs_tiktok_ad_clicked,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_tiktok_click_id")]
        #pragma warning disable CS1591
        Hs_tiktok_click_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_time_between_contact_creation_and_deal_close")]
        #pragma warning disable CS1591
        Hs_time_between_contact_creation_and_deal_close,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_time_between_contact_creation_and_deal_creation")]
        #pragma warning disable CS1591
        Hs_time_between_contact_creation_and_deal_creation,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_time_in_customer")]
        #pragma warning disable CS1591
        Hs_time_in_customer,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_time_in_evangelist")]
        #pragma warning disable CS1591
        Hs_time_in_evangelist,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_time_in_lead")]
        #pragma warning disable CS1591
        Hs_time_in_lead,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_time_in_marketingqualifiedlead")]
        #pragma warning disable CS1591
        Hs_time_in_marketingqualifiedlead,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_time_in_opportunity")]
        #pragma warning disable CS1591
        Hs_time_in_opportunity,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_time_in_other")]
        #pragma warning disable CS1591
        Hs_time_in_other,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_time_in_salesqualifiedlead")]
        #pragma warning disable CS1591
        Hs_time_in_salesqualifiedlead,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_time_in_subscriber")]
        #pragma warning disable CS1591
        Hs_time_in_subscriber,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_time_to_first_engagement")]
        #pragma warning disable CS1591
        Hs_time_to_first_engagement,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_time_to_move_from_lead_to_customer")]
        #pragma warning disable CS1591
        Hs_time_to_move_from_lead_to_customer,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_time_to_move_from_marketingqualifiedlead_to_customer")]
        #pragma warning disable CS1591
        Hs_time_to_move_from_marketingqualifiedlead_to_customer,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_time_to_move_from_opportunity_to_customer")]
        #pragma warning disable CS1591
        Hs_time_to_move_from_opportunity_to_customer,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_time_to_move_from_salesqualifiedlead_to_customer")]
        #pragma warning disable CS1591
        Hs_time_to_move_from_salesqualifiedlead_to_customer,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_time_to_move_from_subscriber_to_customer")]
        #pragma warning disable CS1591
        Hs_time_to_move_from_subscriber_to_customer,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_timezone")]
        #pragma warning disable CS1591
        Hs_timezone,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_twitterid")]
        #pragma warning disable CS1591
        Hs_twitterid,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_v2_cumulative_time_in_customer")]
        #pragma warning disable CS1591
        Hs_v2_cumulative_time_in_customer,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_v2_cumulative_time_in_evangelist")]
        #pragma warning disable CS1591
        Hs_v2_cumulative_time_in_evangelist,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_v2_cumulative_time_in_lead")]
        #pragma warning disable CS1591
        Hs_v2_cumulative_time_in_lead,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_v2_cumulative_time_in_marketingqualifiedlead")]
        #pragma warning disable CS1591
        Hs_v2_cumulative_time_in_marketingqualifiedlead,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_v2_cumulative_time_in_opportunity")]
        #pragma warning disable CS1591
        Hs_v2_cumulative_time_in_opportunity,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_v2_cumulative_time_in_other")]
        #pragma warning disable CS1591
        Hs_v2_cumulative_time_in_other,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_v2_cumulative_time_in_salesqualifiedlead")]
        #pragma warning disable CS1591
        Hs_v2_cumulative_time_in_salesqualifiedlead,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_v2_cumulative_time_in_subscriber")]
        #pragma warning disable CS1591
        Hs_v2_cumulative_time_in_subscriber,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_v2_date_entered_current_stage")]
        #pragma warning disable CS1591
        Hs_v2_date_entered_current_stage,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_v2_date_entered_customer")]
        #pragma warning disable CS1591
        Hs_v2_date_entered_customer,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_v2_date_entered_evangelist")]
        #pragma warning disable CS1591
        Hs_v2_date_entered_evangelist,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_v2_date_entered_lead")]
        #pragma warning disable CS1591
        Hs_v2_date_entered_lead,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_v2_date_entered_marketingqualifiedlead")]
        #pragma warning disable CS1591
        Hs_v2_date_entered_marketingqualifiedlead,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_v2_date_entered_opportunity")]
        #pragma warning disable CS1591
        Hs_v2_date_entered_opportunity,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_v2_date_entered_other")]
        #pragma warning disable CS1591
        Hs_v2_date_entered_other,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_v2_date_entered_salesqualifiedlead")]
        #pragma warning disable CS1591
        Hs_v2_date_entered_salesqualifiedlead,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_v2_date_entered_subscriber")]
        #pragma warning disable CS1591
        Hs_v2_date_entered_subscriber,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_v2_date_exited_customer")]
        #pragma warning disable CS1591
        Hs_v2_date_exited_customer,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_v2_date_exited_evangelist")]
        #pragma warning disable CS1591
        Hs_v2_date_exited_evangelist,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_v2_date_exited_lead")]
        #pragma warning disable CS1591
        Hs_v2_date_exited_lead,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_v2_date_exited_marketingqualifiedlead")]
        #pragma warning disable CS1591
        Hs_v2_date_exited_marketingqualifiedlead,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_v2_date_exited_opportunity")]
        #pragma warning disable CS1591
        Hs_v2_date_exited_opportunity,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_v2_date_exited_other")]
        #pragma warning disable CS1591
        Hs_v2_date_exited_other,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_v2_date_exited_salesqualifiedlead")]
        #pragma warning disable CS1591
        Hs_v2_date_exited_salesqualifiedlead,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_v2_date_exited_subscriber")]
        #pragma warning disable CS1591
        Hs_v2_date_exited_subscriber,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_v2_latest_time_in_customer")]
        #pragma warning disable CS1591
        Hs_v2_latest_time_in_customer,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_v2_latest_time_in_evangelist")]
        #pragma warning disable CS1591
        Hs_v2_latest_time_in_evangelist,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_v2_latest_time_in_lead")]
        #pragma warning disable CS1591
        Hs_v2_latest_time_in_lead,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_v2_latest_time_in_marketingqualifiedlead")]
        #pragma warning disable CS1591
        Hs_v2_latest_time_in_marketingqualifiedlead,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_v2_latest_time_in_opportunity")]
        #pragma warning disable CS1591
        Hs_v2_latest_time_in_opportunity,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_v2_latest_time_in_other")]
        #pragma warning disable CS1591
        Hs_v2_latest_time_in_other,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_v2_latest_time_in_salesqualifiedlead")]
        #pragma warning disable CS1591
        Hs_v2_latest_time_in_salesqualifiedlead,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_v2_latest_time_in_subscriber")]
        #pragma warning disable CS1591
        Hs_v2_latest_time_in_subscriber,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_v2_time_in_current_stage")]
        #pragma warning disable CS1591
        Hs_v2_time_in_current_stage,
        #pragma warning restore CS1591
        [EnumMember(Value = "hs_whatsapp_phone_number")]
        #pragma warning disable CS1591
        Hs_whatsapp_phone_number,
        #pragma warning restore CS1591
        [EnumMember(Value = "hubspot_owner_id")]
        #pragma warning disable CS1591
        Hubspot_owner_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "hubspotscore")]
        #pragma warning disable CS1591
        Hubspotscore,
        #pragma warning restore CS1591
        [EnumMember(Value = "industry")]
        #pragma warning disable CS1591
        Industry,
        #pragma warning restore CS1591
        [EnumMember(Value = "ip_city")]
        #pragma warning disable CS1591
        Ip_city,
        #pragma warning restore CS1591
        [EnumMember(Value = "ip_country")]
        #pragma warning disable CS1591
        Ip_country,
        #pragma warning restore CS1591
        [EnumMember(Value = "ip_country_code")]
        #pragma warning disable CS1591
        Ip_country_code,
        #pragma warning restore CS1591
        [EnumMember(Value = "ip_latlon")]
        #pragma warning disable CS1591
        Ip_latlon,
        #pragma warning restore CS1591
        [EnumMember(Value = "ip_state")]
        #pragma warning disable CS1591
        Ip_state,
        #pragma warning restore CS1591
        [EnumMember(Value = "ip_state_code")]
        #pragma warning disable CS1591
        Ip_state_code,
        #pragma warning restore CS1591
        [EnumMember(Value = "ip_zipcode")]
        #pragma warning disable CS1591
        Ip_zipcode,
        #pragma warning restore CS1591
        [EnumMember(Value = "job_function")]
        #pragma warning disable CS1591
        Job_function,
        #pragma warning restore CS1591
        [EnumMember(Value = "jobtitle")]
        #pragma warning disable CS1591
        Jobtitle,
        #pragma warning restore CS1591
        [EnumMember(Value = "kloutscoregeneral")]
        #pragma warning disable CS1591
        Kloutscoregeneral,
        #pragma warning restore CS1591
        [EnumMember(Value = "lastmodifieddate")]
        #pragma warning disable CS1591
        Lastmodifieddate,
        #pragma warning restore CS1591
        [EnumMember(Value = "lastname")]
        #pragma warning disable CS1591
        Lastname,
        #pragma warning restore CS1591
        [EnumMember(Value = "lifecyclestage")]
        #pragma warning disable CS1591
        Lifecyclestage,
        #pragma warning restore CS1591
        [EnumMember(Value = "linkedinbio")]
        #pragma warning disable CS1591
        Linkedinbio,
        #pragma warning restore CS1591
        [EnumMember(Value = "linkedinconnections")]
        #pragma warning disable CS1591
        Linkedinconnections,
        #pragma warning restore CS1591
        [EnumMember(Value = "marital_status")]
        #pragma warning disable CS1591
        Marital_status,
        #pragma warning restore CS1591
        [EnumMember(Value = "message")]
        #pragma warning disable CS1591
        Message,
        #pragma warning restore CS1591
        [EnumMember(Value = "military_status")]
        #pragma warning disable CS1591
        Military_status,
        #pragma warning restore CS1591
        [EnumMember(Value = "mobilephone")]
        #pragma warning disable CS1591
        Mobilephone,
        #pragma warning restore CS1591
        [EnumMember(Value = "notes_last_contacted")]
        #pragma warning disable CS1591
        Notes_last_contacted,
        #pragma warning restore CS1591
        [EnumMember(Value = "notes_last_updated")]
        #pragma warning disable CS1591
        Notes_last_updated,
        #pragma warning restore CS1591
        [EnumMember(Value = "notes_next_activity_date")]
        #pragma warning disable CS1591
        Notes_next_activity_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "num_associated_deals")]
        #pragma warning disable CS1591
        Num_associated_deals,
        #pragma warning restore CS1591
        [EnumMember(Value = "num_contacted_notes")]
        #pragma warning disable CS1591
        Num_contacted_notes,
        #pragma warning restore CS1591
        [EnumMember(Value = "num_conversion_events")]
        #pragma warning disable CS1591
        Num_conversion_events,
        #pragma warning restore CS1591
        [EnumMember(Value = "num_notes")]
        #pragma warning disable CS1591
        Num_notes,
        #pragma warning restore CS1591
        [EnumMember(Value = "num_unique_conversion_events")]
        #pragma warning disable CS1591
        Num_unique_conversion_events,
        #pragma warning restore CS1591
        [EnumMember(Value = "numemployees")]
        #pragma warning disable CS1591
        Numemployees,
        #pragma warning restore CS1591
        [EnumMember(Value = "owneremail")]
        #pragma warning disable CS1591
        Owneremail,
        #pragma warning restore CS1591
        [EnumMember(Value = "ownername")]
        #pragma warning disable CS1591
        Ownername,
        #pragma warning restore CS1591
        [EnumMember(Value = "phone")]
        #pragma warning disable CS1591
        Phone,
        #pragma warning restore CS1591
        [EnumMember(Value = "photo")]
        #pragma warning disable CS1591
        Photo,
        #pragma warning restore CS1591
        [EnumMember(Value = "recent_conversion_date")]
        #pragma warning disable CS1591
        Recent_conversion_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "recent_conversion_event_name")]
        #pragma warning disable CS1591
        Recent_conversion_event_name,
        #pragma warning restore CS1591
        [EnumMember(Value = "recent_deal_amount")]
        #pragma warning disable CS1591
        Recent_deal_amount,
        #pragma warning restore CS1591
        [EnumMember(Value = "recent_deal_close_date")]
        #pragma warning disable CS1591
        Recent_deal_close_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "relationship_status")]
        #pragma warning disable CS1591
        Relationship_status,
        #pragma warning restore CS1591
        [EnumMember(Value = "salutation")]
        #pragma warning disable CS1591
        Salutation,
        #pragma warning restore CS1591
        [EnumMember(Value = "school")]
        #pragma warning disable CS1591
        School,
        #pragma warning restore CS1591
        [EnumMember(Value = "seniority")]
        #pragma warning disable CS1591
        Seniority,
        #pragma warning restore CS1591
        [EnumMember(Value = "start_date")]
        #pragma warning disable CS1591
        Start_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "state")]
        #pragma warning disable CS1591
        State,
        #pragma warning restore CS1591
        [EnumMember(Value = "surveymonkeyeventlastupdated")]
        #pragma warning disable CS1591
        Surveymonkeyeventlastupdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "total_revenue")]
        #pragma warning disable CS1591
        Total_revenue,
        #pragma warning restore CS1591
        [EnumMember(Value = "twitterbio")]
        #pragma warning disable CS1591
        Twitterbio,
        #pragma warning restore CS1591
        [EnumMember(Value = "twitterhandle")]
        #pragma warning disable CS1591
        Twitterhandle,
        #pragma warning restore CS1591
        [EnumMember(Value = "twitterprofilephoto")]
        #pragma warning disable CS1591
        Twitterprofilephoto,
        #pragma warning restore CS1591
        [EnumMember(Value = "webinareventlastupdated")]
        #pragma warning disable CS1591
        Webinareventlastupdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "website")]
        #pragma warning disable CS1591
        Website,
        #pragma warning restore CS1591
        [EnumMember(Value = "work_email")]
        #pragma warning disable CS1591
        Work_email,
        #pragma warning restore CS1591
        [EnumMember(Value = "zip")]
        #pragma warning disable CS1591
        Zip,
        #pragma warning restore CS1591
    }
}
