// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    /// <summary>The type of filter being applied. This is a string value that specifies the kind of filter operation.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PropertyFilterType
    {
        [EnumMember(Value = "PROPERTY")]
        #pragma warning disable CS1591
        Property,
        #pragma warning restore CS1591
    }
}
