// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    /// <summary>&quot;The thread&apos;s status: `OPEN` or `CLOSED`.&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PublicThread_status
    {
        [EnumMember(Value = "CLOSED")]
        #pragma warning disable CS1591
        CLOSED,
        #pragma warning restore CS1591
        [EnumMember(Value = "OPEN")]
        #pragma warning disable CS1591
        OPEN,
        #pragma warning restore CS1591
    }
}
