// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PublicObjectApprovalStatus : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The unique identifier for the approval process instance associated with this object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApprovalId { get; set; }
#nullable restore
#else
        public string ApprovalId { get; set; }
#endif
        /// <summary>The current approval status of the object. This indicates whether the object is approved, pending approval, or rejected.</summary>
        public global::Soenneker.HubSpot.OpenApiClient.Models.PublicObjectApprovalStatusApprovalStatus? ApprovalStatus { get; set; }
        /// <summary>The date and time when this approval status record was created, in ISO 8601 format.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The unique identifier for this approval status object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The unique identifier of the object whose approval status is being tracked.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ObjectId { get; set; }
#nullable restore
#else
        public string ObjectId { get; set; }
#endif
        /// <summary>The type identifier of the object, indicating what kind of object is being approved.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ObjectTypeId { get; set; }
#nullable restore
#else
        public string ObjectTypeId { get; set; }
#endif
        /// <summary>The unique identifier of the pipeline in which the object is located.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PipelineId { get; set; }
#nullable restore
#else
        public string PipelineId { get; set; }
#endif
        /// <summary>The unique identifier of the pipeline stage where the object currently resides.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PipelineStageId { get; set; }
#nullable restore
#else
        public string PipelineStageId { get; set; }
#endif
        /// <summary>The date and time when this approval status record was last updated, in ISO 8601 format.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicObjectApprovalStatus"/> and sets the default values.
        /// </summary>
        public PublicObjectApprovalStatus()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicObjectApprovalStatus"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HubSpot.OpenApiClient.Models.PublicObjectApprovalStatus CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HubSpot.OpenApiClient.Models.PublicObjectApprovalStatus();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "approvalId", n => { ApprovalId = n.GetStringValue(); } },
                { "approvalStatus", n => { ApprovalStatus = n.GetEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.PublicObjectApprovalStatusApprovalStatus>(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "objectId", n => { ObjectId = n.GetStringValue(); } },
                { "objectTypeId", n => { ObjectTypeId = n.GetStringValue(); } },
                { "pipelineId", n => { PipelineId = n.GetStringValue(); } },
                { "pipelineStageId", n => { PipelineStageId = n.GetStringValue(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("approvalId", ApprovalId);
            writer.WriteEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.PublicObjectApprovalStatusApprovalStatus>("approvalStatus", ApprovalStatus);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("objectId", ObjectId);
            writer.WriteStringValue("objectTypeId", ObjectTypeId);
            writer.WriteStringValue("pipelineId", PipelineId);
            writer.WriteStringValue("pipelineStageId", PipelineStageId);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
