// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    /// <summary>Indicates the type of filter branch, defaulting to NOT_ANY.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PublicNotAnyFilterBranch_filterBranchType
    {
        [EnumMember(Value = "NOT_ANY")]
        #pragma warning disable CS1591
        NOT_ANY,
        #pragma warning restore CS1591
    }
}
