// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    /// <summary>The strategy used for selling, which can be either &apos;LEAD_BASED&apos; or &apos;ACCOUNT_BASED&apos;.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PublicSequenceSettingsResponseSellingStrategy
    {
        [EnumMember(Value = "ACCOUNT_BASED")]
        #pragma warning disable CS1591
        AccountBased,
        #pragma warning restore CS1591
        [EnumMember(Value = "LEAD_BASED")]
        #pragma warning disable CS1591
        LeadBased,
        #pragma warning restore CS1591
    }
}
