// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PublicCtaAnalyticsFilter : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Defines the criteria for refining CTA analytics, using one of several possible schemas such as PublicNumOccurrencesRefineBy or PublicRelativeComparativeTimestampRefineBy.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HubSpot.OpenApiClient.Models.PublicCtaAnalyticsFilter.PublicCtaAnalyticsFilter_coalescingRefineBy? CoalescingRefineBy { get; set; }
#nullable restore
#else
        public global::Soenneker.HubSpot.OpenApiClient.Models.PublicCtaAnalyticsFilter.PublicCtaAnalyticsFilter_coalescingRefineBy CoalescingRefineBy { get; set; }
#endif
        /// <summary>The name of the call-to-action (CTA) used in the analytics filter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CtaName { get; set; }
#nullable restore
#else
        public string CtaName { get; set; }
#endif
        /// <summary>Indicates the type of filter, which defaults to CTA.</summary>
        public global::Soenneker.HubSpot.OpenApiClient.Models.PublicCtaAnalyticsFilter_filterType? FilterType { get; set; }
        /// <summary>Specifies the operator used in the CTA analytics filter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Operator { get; set; }
#nullable restore
#else
        public string Operator { get; set; }
#endif
        /// <summary>Specifies the criteria for pruning CTA analytics, using one of several possible schemas such as PublicNumOccurrencesRefineBy or PublicRelativeRangedTimestampRefineBy.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HubSpot.OpenApiClient.Models.PublicCtaAnalyticsFilter.PublicCtaAnalyticsFilter_pruningRefineBy? PruningRefineBy { get; set; }
#nullable restore
#else
        public global::Soenneker.HubSpot.OpenApiClient.Models.PublicCtaAnalyticsFilter.PublicCtaAnalyticsFilter_pruningRefineBy PruningRefineBy { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicCtaAnalyticsFilter"/> and sets the default values.
        /// </summary>
        public PublicCtaAnalyticsFilter()
        {
            AdditionalData = new Dictionary<string, object>();
            FilterType = global::Soenneker.HubSpot.OpenApiClient.Models.PublicCtaAnalyticsFilter_filterType.CTA;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicCtaAnalyticsFilter"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HubSpot.OpenApiClient.Models.PublicCtaAnalyticsFilter CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HubSpot.OpenApiClient.Models.PublicCtaAnalyticsFilter();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "coalescingRefineBy", n => { CoalescingRefineBy = n.GetObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.PublicCtaAnalyticsFilter.PublicCtaAnalyticsFilter_coalescingRefineBy>(global::Soenneker.HubSpot.OpenApiClient.Models.PublicCtaAnalyticsFilter.PublicCtaAnalyticsFilter_coalescingRefineBy.CreateFromDiscriminatorValue); } },
                { "ctaName", n => { CtaName = n.GetStringValue(); } },
                { "filterType", n => { FilterType = n.GetEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.PublicCtaAnalyticsFilter_filterType>(); } },
                { "operator", n => { Operator = n.GetStringValue(); } },
                { "pruningRefineBy", n => { PruningRefineBy = n.GetObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.PublicCtaAnalyticsFilter.PublicCtaAnalyticsFilter_pruningRefineBy>(global::Soenneker.HubSpot.OpenApiClient.Models.PublicCtaAnalyticsFilter.PublicCtaAnalyticsFilter_pruningRefineBy.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.PublicCtaAnalyticsFilter.PublicCtaAnalyticsFilter_coalescingRefineBy>("coalescingRefineBy", CoalescingRefineBy);
            writer.WriteStringValue("ctaName", CtaName);
            writer.WriteEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.PublicCtaAnalyticsFilter_filterType>("filterType", FilterType);
            writer.WriteStringValue("operator", Operator);
            writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.PublicCtaAnalyticsFilter.PublicCtaAnalyticsFilter_pruningRefineBy>("pruningRefineBy", PruningRefineBy);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicAbsoluteComparativeTimestampRefineBy"/>, <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicAbsoluteRangedTimestampRefineBy"/>, <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicAllHistoryRefineBy"/>, <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicNumOccurrencesRefineBy"/>, <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicRangedTimeOperation"/>, <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicRelativeComparativeTimestampRefineBy"/>, <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicRelativeRangedTimestampRefineBy"/>, <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicSetOccurrencesRefineBy"/>, <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicTimePointOperation"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PublicCtaAnalyticsFilter_coalescingRefineBy : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicAbsoluteComparativeTimestampRefineBy"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicAbsoluteComparativeTimestampRefineBy? PublicAbsoluteComparativeTimestampRefineBy { get; set; }
#nullable restore
#else
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicAbsoluteComparativeTimestampRefineBy PublicAbsoluteComparativeTimestampRefineBy { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicAbsoluteRangedTimestampRefineBy"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicAbsoluteRangedTimestampRefineBy? PublicAbsoluteRangedTimestampRefineBy { get; set; }
#nullable restore
#else
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicAbsoluteRangedTimestampRefineBy PublicAbsoluteRangedTimestampRefineBy { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicAllHistoryRefineBy"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicAllHistoryRefineBy? PublicAllHistoryRefineBy { get; set; }
#nullable restore
#else
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicAllHistoryRefineBy PublicAllHistoryRefineBy { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicNumOccurrencesRefineBy"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicNumOccurrencesRefineBy? PublicNumOccurrencesRefineBy { get; set; }
#nullable restore
#else
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicNumOccurrencesRefineBy PublicNumOccurrencesRefineBy { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicRangedTimeOperation"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicRangedTimeOperation? PublicRangedTimeOperation { get; set; }
#nullable restore
#else
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicRangedTimeOperation PublicRangedTimeOperation { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicRelativeComparativeTimestampRefineBy"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicRelativeComparativeTimestampRefineBy? PublicRelativeComparativeTimestampRefineBy { get; set; }
#nullable restore
#else
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicRelativeComparativeTimestampRefineBy PublicRelativeComparativeTimestampRefineBy { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicRelativeRangedTimestampRefineBy"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicRelativeRangedTimestampRefineBy? PublicRelativeRangedTimestampRefineBy { get; set; }
#nullable restore
#else
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicRelativeRangedTimestampRefineBy PublicRelativeRangedTimestampRefineBy { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicSetOccurrencesRefineBy"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicSetOccurrencesRefineBy? PublicSetOccurrencesRefineBy { get; set; }
#nullable restore
#else
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicSetOccurrencesRefineBy PublicSetOccurrencesRefineBy { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicTimePointOperation"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicTimePointOperation? PublicTimePointOperation { get; set; }
#nullable restore
#else
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicTimePointOperation PublicTimePointOperation { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicCtaAnalyticsFilter.PublicCtaAnalyticsFilter_coalescingRefineBy"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.HubSpot.OpenApiClient.Models.PublicCtaAnalyticsFilter.PublicCtaAnalyticsFilter_coalescingRefineBy CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.HubSpot.OpenApiClient.Models.PublicCtaAnalyticsFilter.PublicCtaAnalyticsFilter_coalescingRefineBy();
                if("PublicAbsoluteComparativeTimestampRefineBy".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PublicAbsoluteComparativeTimestampRefineBy = new global::Soenneker.HubSpot.OpenApiClient.Models.PublicAbsoluteComparativeTimestampRefineBy();
                }
                else if("PublicAbsoluteRangedTimestampRefineBy".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PublicAbsoluteRangedTimestampRefineBy = new global::Soenneker.HubSpot.OpenApiClient.Models.PublicAbsoluteRangedTimestampRefineBy();
                }
                else if("PublicAllHistoryRefineBy".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PublicAllHistoryRefineBy = new global::Soenneker.HubSpot.OpenApiClient.Models.PublicAllHistoryRefineBy();
                }
                else if("PublicNumOccurrencesRefineBy".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PublicNumOccurrencesRefineBy = new global::Soenneker.HubSpot.OpenApiClient.Models.PublicNumOccurrencesRefineBy();
                }
                else if("PublicRangedTimeOperation".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PublicRangedTimeOperation = new global::Soenneker.HubSpot.OpenApiClient.Models.PublicRangedTimeOperation();
                }
                else if("PublicRelativeComparativeTimestampRefineBy".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PublicRelativeComparativeTimestampRefineBy = new global::Soenneker.HubSpot.OpenApiClient.Models.PublicRelativeComparativeTimestampRefineBy();
                }
                else if("PublicRelativeRangedTimestampRefineBy".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PublicRelativeRangedTimestampRefineBy = new global::Soenneker.HubSpot.OpenApiClient.Models.PublicRelativeRangedTimestampRefineBy();
                }
                else if("PublicSetOccurrencesRefineBy".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PublicSetOccurrencesRefineBy = new global::Soenneker.HubSpot.OpenApiClient.Models.PublicSetOccurrencesRefineBy();
                }
                else if("PublicTimePointOperation".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PublicTimePointOperation = new global::Soenneker.HubSpot.OpenApiClient.Models.PublicTimePointOperation();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(PublicAbsoluteComparativeTimestampRefineBy != null)
                {
                    return PublicAbsoluteComparativeTimestampRefineBy.GetFieldDeserializers();
                }
                else if(PublicAbsoluteRangedTimestampRefineBy != null)
                {
                    return PublicAbsoluteRangedTimestampRefineBy.GetFieldDeserializers();
                }
                else if(PublicAllHistoryRefineBy != null)
                {
                    return PublicAllHistoryRefineBy.GetFieldDeserializers();
                }
                else if(PublicNumOccurrencesRefineBy != null)
                {
                    return PublicNumOccurrencesRefineBy.GetFieldDeserializers();
                }
                else if(PublicRangedTimeOperation != null)
                {
                    return PublicRangedTimeOperation.GetFieldDeserializers();
                }
                else if(PublicRelativeComparativeTimestampRefineBy != null)
                {
                    return PublicRelativeComparativeTimestampRefineBy.GetFieldDeserializers();
                }
                else if(PublicRelativeRangedTimestampRefineBy != null)
                {
                    return PublicRelativeRangedTimestampRefineBy.GetFieldDeserializers();
                }
                else if(PublicSetOccurrencesRefineBy != null)
                {
                    return PublicSetOccurrencesRefineBy.GetFieldDeserializers();
                }
                else if(PublicTimePointOperation != null)
                {
                    return PublicTimePointOperation.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(PublicAbsoluteComparativeTimestampRefineBy != null)
                {
                    writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.PublicAbsoluteComparativeTimestampRefineBy>(null, PublicAbsoluteComparativeTimestampRefineBy);
                }
                else if(PublicAbsoluteRangedTimestampRefineBy != null)
                {
                    writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.PublicAbsoluteRangedTimestampRefineBy>(null, PublicAbsoluteRangedTimestampRefineBy);
                }
                else if(PublicAllHistoryRefineBy != null)
                {
                    writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.PublicAllHistoryRefineBy>(null, PublicAllHistoryRefineBy);
                }
                else if(PublicNumOccurrencesRefineBy != null)
                {
                    writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.PublicNumOccurrencesRefineBy>(null, PublicNumOccurrencesRefineBy);
                }
                else if(PublicRangedTimeOperation != null)
                {
                    writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.PublicRangedTimeOperation>(null, PublicRangedTimeOperation);
                }
                else if(PublicRelativeComparativeTimestampRefineBy != null)
                {
                    writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.PublicRelativeComparativeTimestampRefineBy>(null, PublicRelativeComparativeTimestampRefineBy);
                }
                else if(PublicRelativeRangedTimestampRefineBy != null)
                {
                    writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.PublicRelativeRangedTimestampRefineBy>(null, PublicRelativeRangedTimestampRefineBy);
                }
                else if(PublicSetOccurrencesRefineBy != null)
                {
                    writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.PublicSetOccurrencesRefineBy>(null, PublicSetOccurrencesRefineBy);
                }
                else if(PublicTimePointOperation != null)
                {
                    writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.PublicTimePointOperation>(null, PublicTimePointOperation);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicAbsoluteComparativeTimestampRefineBy"/>, <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicAbsoluteRangedTimestampRefineBy"/>, <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicAllHistoryRefineBy"/>, <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicNumOccurrencesRefineBy"/>, <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicRangedTimeOperation"/>, <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicRelativeComparativeTimestampRefineBy"/>, <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicRelativeRangedTimestampRefineBy"/>, <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicSetOccurrencesRefineBy"/>, <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicTimePointOperation"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PublicCtaAnalyticsFilter_pruningRefineBy : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicAbsoluteComparativeTimestampRefineBy"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicAbsoluteComparativeTimestampRefineBy? PublicAbsoluteComparativeTimestampRefineBy { get; set; }
#nullable restore
#else
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicAbsoluteComparativeTimestampRefineBy PublicAbsoluteComparativeTimestampRefineBy { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicAbsoluteRangedTimestampRefineBy"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicAbsoluteRangedTimestampRefineBy? PublicAbsoluteRangedTimestampRefineBy { get; set; }
#nullable restore
#else
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicAbsoluteRangedTimestampRefineBy PublicAbsoluteRangedTimestampRefineBy { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicAllHistoryRefineBy"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicAllHistoryRefineBy? PublicAllHistoryRefineBy { get; set; }
#nullable restore
#else
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicAllHistoryRefineBy PublicAllHistoryRefineBy { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicNumOccurrencesRefineBy"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicNumOccurrencesRefineBy? PublicNumOccurrencesRefineBy { get; set; }
#nullable restore
#else
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicNumOccurrencesRefineBy PublicNumOccurrencesRefineBy { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicRangedTimeOperation"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicRangedTimeOperation? PublicRangedTimeOperation { get; set; }
#nullable restore
#else
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicRangedTimeOperation PublicRangedTimeOperation { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicRelativeComparativeTimestampRefineBy"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicRelativeComparativeTimestampRefineBy? PublicRelativeComparativeTimestampRefineBy { get; set; }
#nullable restore
#else
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicRelativeComparativeTimestampRefineBy PublicRelativeComparativeTimestampRefineBy { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicRelativeRangedTimestampRefineBy"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicRelativeRangedTimestampRefineBy? PublicRelativeRangedTimestampRefineBy { get; set; }
#nullable restore
#else
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicRelativeRangedTimestampRefineBy PublicRelativeRangedTimestampRefineBy { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicSetOccurrencesRefineBy"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicSetOccurrencesRefineBy? PublicSetOccurrencesRefineBy { get; set; }
#nullable restore
#else
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicSetOccurrencesRefineBy PublicSetOccurrencesRefineBy { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicTimePointOperation"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicTimePointOperation? PublicTimePointOperation { get; set; }
#nullable restore
#else
            public global::Soenneker.HubSpot.OpenApiClient.Models.PublicTimePointOperation PublicTimePointOperation { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicCtaAnalyticsFilter.PublicCtaAnalyticsFilter_pruningRefineBy"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.HubSpot.OpenApiClient.Models.PublicCtaAnalyticsFilter.PublicCtaAnalyticsFilter_pruningRefineBy CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.HubSpot.OpenApiClient.Models.PublicCtaAnalyticsFilter.PublicCtaAnalyticsFilter_pruningRefineBy();
                if("PublicAbsoluteComparativeTimestampRefineBy".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PublicAbsoluteComparativeTimestampRefineBy = new global::Soenneker.HubSpot.OpenApiClient.Models.PublicAbsoluteComparativeTimestampRefineBy();
                }
                else if("PublicAbsoluteRangedTimestampRefineBy".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PublicAbsoluteRangedTimestampRefineBy = new global::Soenneker.HubSpot.OpenApiClient.Models.PublicAbsoluteRangedTimestampRefineBy();
                }
                else if("PublicAllHistoryRefineBy".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PublicAllHistoryRefineBy = new global::Soenneker.HubSpot.OpenApiClient.Models.PublicAllHistoryRefineBy();
                }
                else if("PublicNumOccurrencesRefineBy".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PublicNumOccurrencesRefineBy = new global::Soenneker.HubSpot.OpenApiClient.Models.PublicNumOccurrencesRefineBy();
                }
                else if("PublicRangedTimeOperation".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PublicRangedTimeOperation = new global::Soenneker.HubSpot.OpenApiClient.Models.PublicRangedTimeOperation();
                }
                else if("PublicRelativeComparativeTimestampRefineBy".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PublicRelativeComparativeTimestampRefineBy = new global::Soenneker.HubSpot.OpenApiClient.Models.PublicRelativeComparativeTimestampRefineBy();
                }
                else if("PublicRelativeRangedTimestampRefineBy".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PublicRelativeRangedTimestampRefineBy = new global::Soenneker.HubSpot.OpenApiClient.Models.PublicRelativeRangedTimestampRefineBy();
                }
                else if("PublicSetOccurrencesRefineBy".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PublicSetOccurrencesRefineBy = new global::Soenneker.HubSpot.OpenApiClient.Models.PublicSetOccurrencesRefineBy();
                }
                else if("PublicTimePointOperation".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PublicTimePointOperation = new global::Soenneker.HubSpot.OpenApiClient.Models.PublicTimePointOperation();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(PublicAbsoluteComparativeTimestampRefineBy != null)
                {
                    return PublicAbsoluteComparativeTimestampRefineBy.GetFieldDeserializers();
                }
                else if(PublicAbsoluteRangedTimestampRefineBy != null)
                {
                    return PublicAbsoluteRangedTimestampRefineBy.GetFieldDeserializers();
                }
                else if(PublicAllHistoryRefineBy != null)
                {
                    return PublicAllHistoryRefineBy.GetFieldDeserializers();
                }
                else if(PublicNumOccurrencesRefineBy != null)
                {
                    return PublicNumOccurrencesRefineBy.GetFieldDeserializers();
                }
                else if(PublicRangedTimeOperation != null)
                {
                    return PublicRangedTimeOperation.GetFieldDeserializers();
                }
                else if(PublicRelativeComparativeTimestampRefineBy != null)
                {
                    return PublicRelativeComparativeTimestampRefineBy.GetFieldDeserializers();
                }
                else if(PublicRelativeRangedTimestampRefineBy != null)
                {
                    return PublicRelativeRangedTimestampRefineBy.GetFieldDeserializers();
                }
                else if(PublicSetOccurrencesRefineBy != null)
                {
                    return PublicSetOccurrencesRefineBy.GetFieldDeserializers();
                }
                else if(PublicTimePointOperation != null)
                {
                    return PublicTimePointOperation.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(PublicAbsoluteComparativeTimestampRefineBy != null)
                {
                    writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.PublicAbsoluteComparativeTimestampRefineBy>(null, PublicAbsoluteComparativeTimestampRefineBy);
                }
                else if(PublicAbsoluteRangedTimestampRefineBy != null)
                {
                    writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.PublicAbsoluteRangedTimestampRefineBy>(null, PublicAbsoluteRangedTimestampRefineBy);
                }
                else if(PublicAllHistoryRefineBy != null)
                {
                    writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.PublicAllHistoryRefineBy>(null, PublicAllHistoryRefineBy);
                }
                else if(PublicNumOccurrencesRefineBy != null)
                {
                    writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.PublicNumOccurrencesRefineBy>(null, PublicNumOccurrencesRefineBy);
                }
                else if(PublicRangedTimeOperation != null)
                {
                    writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.PublicRangedTimeOperation>(null, PublicRangedTimeOperation);
                }
                else if(PublicRelativeComparativeTimestampRefineBy != null)
                {
                    writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.PublicRelativeComparativeTimestampRefineBy>(null, PublicRelativeComparativeTimestampRefineBy);
                }
                else if(PublicRelativeRangedTimestampRefineBy != null)
                {
                    writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.PublicRelativeRangedTimestampRefineBy>(null, PublicRelativeRangedTimestampRefineBy);
                }
                else if(PublicSetOccurrencesRefineBy != null)
                {
                    writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.PublicSetOccurrencesRefineBy>(null, PublicSetOccurrencesRefineBy);
                }
                else if(PublicTimePointOperation != null)
                {
                    writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.PublicTimePointOperation>(null, PublicTimePointOperation);
                }
            }
        }
    }
}
#pragma warning restore CS0618
