// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PublicConversationsMessageEgg : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The attachments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.HubSpot.OpenApiClient.Models.PublicConversationsMessageEggAttachmentsItem>? Attachments { get; set; }
#nullable restore
#else
        public List<global::Soenneker.HubSpot.OpenApiClient.Models.PublicConversationsMessageEggAttachmentsItem> Attachments { get; set; }
#endif
        /// <summary>The channelAccountId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChannelAccountId { get; set; }
#nullable restore
#else
        public string ChannelAccountId { get; set; }
#endif
        /// <summary>The channelId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChannelId { get; set; }
#nullable restore
#else
        public string ChannelId { get; set; }
#endif
        /// <summary>The recipients property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.HubSpot.OpenApiClient.Models.PublicRecipientEgg>? Recipients { get; set; }
#nullable restore
#else
        public List<global::Soenneker.HubSpot.OpenApiClient.Models.PublicRecipientEgg> Recipients { get; set; }
#endif
        /// <summary>The richText property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RichText { get; set; }
#nullable restore
#else
        public string RichText { get; set; }
#endif
        /// <summary>The senderActorId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SenderActorId { get; set; }
#nullable restore
#else
        public string SenderActorId { get; set; }
#endif
        /// <summary>The subject property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>The text property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.HubSpot.OpenApiClient.Models.PublicConversationsMessageEggType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicConversationsMessageEgg"/> and sets the default values.
        /// </summary>
        public PublicConversationsMessageEgg()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicConversationsMessageEgg"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HubSpot.OpenApiClient.Models.PublicConversationsMessageEgg CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HubSpot.OpenApiClient.Models.PublicConversationsMessageEgg();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attachments", n => { Attachments = n.GetCollectionOfObjectValues<global::Soenneker.HubSpot.OpenApiClient.Models.PublicConversationsMessageEggAttachmentsItem>(global::Soenneker.HubSpot.OpenApiClient.Models.PublicConversationsMessageEggAttachmentsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "channelAccountId", n => { ChannelAccountId = n.GetStringValue(); } },
                { "channelId", n => { ChannelId = n.GetStringValue(); } },
                { "recipients", n => { Recipients = n.GetCollectionOfObjectValues<global::Soenneker.HubSpot.OpenApiClient.Models.PublicRecipientEgg>(global::Soenneker.HubSpot.OpenApiClient.Models.PublicRecipientEgg.CreateFromDiscriminatorValue)?.AsList(); } },
                { "richText", n => { RichText = n.GetStringValue(); } },
                { "senderActorId", n => { SenderActorId = n.GetStringValue(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
                { "text", n => { Text = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.PublicConversationsMessageEggType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.HubSpot.OpenApiClient.Models.PublicConversationsMessageEggAttachmentsItem>("attachments", Attachments);
            writer.WriteStringValue("channelAccountId", ChannelAccountId);
            writer.WriteStringValue("channelId", ChannelId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.HubSpot.OpenApiClient.Models.PublicRecipientEgg>("recipients", Recipients);
            writer.WriteStringValue("richText", RichText);
            writer.WriteStringValue("senderActorId", SenderActorId);
            writer.WriteStringValue("subject", Subject);
            writer.WriteStringValue("text", Text);
            writer.WriteEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.PublicConversationsMessageEggType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
