// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    /// <summary>A string specifying the parser to use for the property, with options including &apos;VALUE&apos;, &apos;UPDATED_AT&apos;, &apos;ANNIVERSARY&apos;, &apos;VALUE_WITH_ZONE_SAME_LOCAL_CONVERSION&apos;, and &apos;ANNIVERSARY_WITH_ZONE_SAME_LOCAL_CONVERSION&apos;.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RangedTimeOperationPropertyParser
    {
        [EnumMember(Value = "ANNIVERSARY")]
        #pragma warning disable CS1591
        Anniversary,
        #pragma warning restore CS1591
        [EnumMember(Value = "ANNIVERSARY_WITH_ZONE_SAME_LOCAL_CONVERSION")]
        #pragma warning disable CS1591
        AnniversaryWithZoneSameLocalConversion,
        #pragma warning restore CS1591
        [EnumMember(Value = "UPDATED_AT")]
        #pragma warning disable CS1591
        UpdatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "VALUE")]
        #pragma warning disable CS1591
        Value,
        #pragma warning restore CS1591
        [EnumMember(Value = "VALUE_WITH_ZONE_SAME_LOCAL_CONVERSION")]
        #pragma warning disable CS1591
        ValueWithZoneSameLocalConversion,
        #pragma warning restore CS1591
    }
}
