// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    /// <summary>A string indicating the type of operation, defaulting to &apos;ROLLING_PROPERTY_UPDATED&apos;.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RollingPropertyUpdatedOperationType
    {
        [EnumMember(Value = "ROLLING_PROPERTY_UPDATED")]
        #pragma warning disable CS1591
        RollingPropertyUpdated,
        #pragma warning restore CS1591
    }
}
