// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    /// <summary>A string that specifies the type of actor, which is &apos;SYSTEM&apos; for this component.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SystemType
    {
        [EnumMember(Value = "SYSTEM")]
        #pragma warning disable CS1591
        System,
        #pragma warning restore CS1591
    }
}
