// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum TimePointOperationPropertyParser
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ANNIVERSARY")]
        #pragma warning disable CS1591
        Anniversary,
        #pragma warning restore CS1591
        [EnumMember(Value = "ANNIVERSARY_WITH_ZONE_SAME_LOCAL_CONVERSION")]
        #pragma warning disable CS1591
        AnniversaryWithZoneSameLocalConversion,
        #pragma warning restore CS1591
        [EnumMember(Value = "UPDATED_AT")]
        #pragma warning disable CS1591
        UpdatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "VALUE")]
        #pragma warning disable CS1591
        Value,
        #pragma warning restore CS1591
        [EnumMember(Value = "VALUE_WITH_ZONE_SAME_LOCAL_CONVERSION")]
        #pragma warning disable CS1591
        ValueWithZoneSameLocalConversion,
        #pragma warning restore CS1591
    }
}
