// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    /// <summary>Specifies the type of operation (TIME_POINT).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TimePointOperationType
    {
        [EnumMember(Value = "TIME_POINT")]
        #pragma warning disable CS1591
        TimePoint,
        #pragma warning restore CS1591
    }
}
