// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    /// <summary>A string indicating the type of property, defaulting to &apos;timepoint&apos;.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TimepointPropertyType
    {
        [EnumMember(Value = "timepoint")]
        #pragma warning disable CS1591
        Timepoint,
        #pragma warning restore CS1591
    }
}
