// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.HubSpot.OpenApiClient.Automation.Sequences.TwoZeroTwoSixZeroNine.Serviceaccounts.Sequences.Item.Performance;
using Soenneker.HubSpot.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Automation.Sequences.TwoZeroTwoSixZeroNine.Serviceaccounts.Sequences.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \automation\sequences\2026-09\serviceaccounts\sequences\{sequenceId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithSequenceItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The performance property</summary>
        public global::Soenneker.HubSpot.OpenApiClient.Automation.Sequences.TwoZeroTwoSixZeroNine.Serviceaccounts.Sequences.Item.Performance.PerformanceRequestBuilder Performance
        {
            get => new global::Soenneker.HubSpot.OpenApiClient.Automation.Sequences.TwoZeroTwoSixZeroNine.Serviceaccounts.Sequences.Item.Performance.PerformanceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HubSpot.OpenApiClient.Automation.Sequences.TwoZeroTwoSixZeroNine.Serviceaccounts.Sequences.Item.WithSequenceItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSequenceItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/automation/sequences/2026-09/serviceaccounts/sequences/{sequenceId}{?overrideActiveEnrollment*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HubSpot.OpenApiClient.Automation.Sequences.TwoZeroTwoSixZeroNine.Serviceaccounts.Sequences.Item.WithSequenceItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSequenceItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/automation/sequences/2026-09/serviceaccounts/sequences/{sequenceId}{?overrideActiveEnrollment*}", rawUrl)
        {
        }
        /// <summary>
        /// Delete a specific sequence in your HubSpot account using its unique identifier. This operation will remove the sequence and can optionally override active enrollments if specified. Please note: the scopes for this endpoint requires user-level access and will not work for existing apps with portal-level access.
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task DeleteAsync(Action<RequestConfiguration<global::Soenneker.HubSpot.OpenApiClient.Automation.Sequences.TwoZeroTwoSixZeroNine.Serviceaccounts.Sequences.Item.WithSequenceItemRequestBuilder.WithSequenceItemRequestBuilderDeleteQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task DeleteAsync(Action<RequestConfiguration<global::Soenneker.HubSpot.OpenApiClient.Automation.Sequences.TwoZeroTwoSixZeroNine.Serviceaccounts.Sequences.Item.WithSequenceItemRequestBuilder.WithSequenceItemRequestBuilderDeleteQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            await RequestAdapter.SendNoContentAsync(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve details of a specific sequence in your HubSpot account using the sequence ID. This endpoint provides comprehensive information about the sequence, including its settings, steps, and dependencies. It is useful for obtaining sequence configurations and understanding the sequence&apos;s structure and components. Please note: the scopes for this endpoint requires user-level access and will not work for existing apps with portal-level access.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicSequenceResponseV2"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.HubSpot.OpenApiClient.Models.PublicSequenceResponseV2?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.HubSpot.OpenApiClient.Models.PublicSequenceResponseV2> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.HubSpot.OpenApiClient.Models.PublicSequenceResponseV2>(requestInfo, global::Soenneker.HubSpot.OpenApiClient.Models.PublicSequenceResponseV2.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update an existing sequence in your HubSpot account using its unique identifier. This endpoint allows you to modify the sequence settings, steps, and dependencies. Ensure that the sequenceId provided in the path is valid and corresponds to the sequence you wish to update. Please note: the scopes for this endpoint requires user-level access and will not work for existing apps with portal-level access.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.PublicSequenceResponseV2"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.HubSpot.OpenApiClient.Models.PublicSequenceResponseV2?> PutAsync(global::Soenneker.HubSpot.OpenApiClient.Models.PublicSequenceRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.HubSpot.OpenApiClient.Models.PublicSequenceResponseV2> PutAsync(global::Soenneker.HubSpot.OpenApiClient.Models.PublicSequenceRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.HubSpot.OpenApiClient.Models.PublicSequenceResponseV2>(requestInfo, global::Soenneker.HubSpot.OpenApiClient.Models.PublicSequenceResponseV2.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Delete a specific sequence in your HubSpot account using its unique identifier. This operation will remove the sequence and can optionally override active enrollments if specified. Please note: the scopes for this endpoint requires user-level access and will not work for existing apps with portal-level access.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Soenneker.HubSpot.OpenApiClient.Automation.Sequences.TwoZeroTwoSixZeroNine.Serviceaccounts.Sequences.Item.WithSequenceItemRequestBuilder.WithSequenceItemRequestBuilderDeleteQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Soenneker.HubSpot.OpenApiClient.Automation.Sequences.TwoZeroTwoSixZeroNine.Serviceaccounts.Sequences.Item.WithSequenceItemRequestBuilder.WithSequenceItemRequestBuilderDeleteQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            return requestInfo;
        }
        /// <summary>
        /// Retrieve details of a specific sequence in your HubSpot account using the sequence ID. This endpoint provides comprehensive information about the sequence, including its settings, steps, and dependencies. It is useful for obtaining sequence configurations and understanding the sequence&apos;s structure and components. Please note: the scopes for this endpoint requires user-level access and will not work for existing apps with portal-level access.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Update an existing sequence in your HubSpot account using its unique identifier. This endpoint allows you to modify the sequence settings, steps, and dependencies. Ensure that the sequenceId provided in the path is valid and corresponds to the sequence you wish to update. Please note: the scopes for this endpoint requires user-level access and will not work for existing apps with portal-level access.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::Soenneker.HubSpot.OpenApiClient.Models.PublicSequenceRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::Soenneker.HubSpot.OpenApiClient.Models.PublicSequenceRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HubSpot.OpenApiClient.Automation.Sequences.TwoZeroTwoSixZeroNine.Serviceaccounts.Sequences.Item.WithSequenceItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.HubSpot.OpenApiClient.Automation.Sequences.TwoZeroTwoSixZeroNine.Serviceaccounts.Sequences.Item.WithSequenceItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.HubSpot.OpenApiClient.Automation.Sequences.TwoZeroTwoSixZeroNine.Serviceaccounts.Sequences.Item.WithSequenceItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Delete a specific sequence in your HubSpot account using its unique identifier. This operation will remove the sequence and can optionally override active enrollments if specified. Please note: the scopes for this endpoint requires user-level access and will not work for existing apps with portal-level access.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithSequenceItemRequestBuilderDeleteQueryParameters 
        {
            /// <summary>A boolean indicating whether to override active enrollments when deleting the sequence.</summary>
            [QueryParameter("overrideActiveEnrollment")]
            public bool? OverrideActiveEnrollment { get; set; }
        }
    }
}
#pragma warning restore CS0618
