// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.HubSpot.OpenApiClient.Cms.Blogs.V3.Posts.Cursor;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Cms.Blogs.V3.Posts
{
    /// <summary>
    /// Builds and executes requests for operations under \cms\blogs\v3\posts
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PostsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The cursor property</summary>
        public global::Soenneker.HubSpot.OpenApiClient.Cms.Blogs.V3.Posts.Cursor.CursorRequestBuilder Cursor
        {
            get => new global::Soenneker.HubSpot.OpenApiClient.Cms.Blogs.V3.Posts.Cursor.CursorRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HubSpot.OpenApiClient.Cms.Blogs.V3.Posts.PostsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PostsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/cms/blogs/v3/posts", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HubSpot.OpenApiClient.Cms.Blogs.V3.Posts.PostsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PostsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/cms/blogs/v3/posts", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
