// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.HubSpot.OpenApiClient.WebhooksJournal.JournalLocal.TwoZeroTwoSixZeroThree.Batch.Earliest.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.HubSpot.OpenApiClient.WebhooksJournal.JournalLocal.TwoZeroTwoSixZeroThree.Batch.Earliest
{
    /// <summary>
    /// Builds and executes requests for operations under \webhooks-journal\journal-local\2026-03\batch\earliest
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EarliestRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.HubSpot.OpenApiClient.webhooksJournal.journalLocal.TwoZeroTwoSixZeroThree.batch.earliest.item collection</summary>
        /// <param name="position">The number of earliest webhook journal entries to retrieve. This is a required integer parameter with a minimum value of 1.</param>
        /// <returns>A <see cref="global::Soenneker.HubSpot.OpenApiClient.WebhooksJournal.JournalLocal.TwoZeroTwoSixZeroThree.Batch.Earliest.Item.WithCountItemRequestBuilder"/></returns>
        public global::Soenneker.HubSpot.OpenApiClient.WebhooksJournal.JournalLocal.TwoZeroTwoSixZeroThree.Batch.Earliest.Item.WithCountItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("count", position);
                return new global::Soenneker.HubSpot.OpenApiClient.WebhooksJournal.JournalLocal.TwoZeroTwoSixZeroThree.Batch.Earliest.Item.WithCountItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HubSpot.OpenApiClient.WebhooksJournal.JournalLocal.TwoZeroTwoSixZeroThree.Batch.Earliest.EarliestRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EarliestRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/webhooks-journal/journal-local/2026-03/batch/earliest", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HubSpot.OpenApiClient.WebhooksJournal.JournalLocal.TwoZeroTwoSixZeroThree.Batch.Earliest.EarliestRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EarliestRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/webhooks-journal/journal-local/2026-03/batch/earliest", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
