// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    /// <summary>Indicates the type of timestamp refinement, which defaults to ABSOLUTE_RANGED.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Automation_Automation_V4_PublicAbsoluteRangedTimestampRefineBy_type
    {
        [EnumMember(Value = "ABSOLUTE_RANGED")]
        #pragma warning disable CS1591
        ABSOLUTE_RANGED,
        #pragma warning restore CS1591
    }
}
