// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    /// <summary>Indicates the type of data value, which defaults to FIELD_DATA.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Automation_Automation_V4_ApiActionDataValue_type
    {
        [EnumMember(Value = "FIELD_DATA")]
        #pragma warning disable CS1591
        FIELD_DATA,
        #pragma warning restore CS1591
    }
}
