// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    /// <summary>Specifies the type of operation, which defaults to &apos;STRING&apos;.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Automation_Automation_V4_PublicStringPropertyOperation_operationType
    {
        [EnumMember(Value = "STRING")]
        #pragma warning disable CS1591
        STRING,
        #pragma warning restore CS1591
    }
}
