// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    /// <summary>The unit of time for the inactivity period, such as (DAY, MONTH, WEEK).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CRM_Lists_PublicListConversionInactivity_timeUnit
    {
        [EnumMember(Value = "DAY")]
        #pragma warning disable CS1591
        DAY,
        #pragma warning restore CS1591
        [EnumMember(Value = "MONTH")]
        #pragma warning disable CS1591
        MONTH,
        #pragma warning restore CS1591
        [EnumMember(Value = "WEEK")]
        #pragma warning disable CS1591
        WEEK,
        #pragma warning restore CS1591
    }
}
