// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CRM_Deal_Splits_BatchResponseDealToDealSplits : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The timestamp indicating when the batch operation was completed, in date-time format.</summary>
        public DateTimeOffset? CompletedAt { get; set; }
        /// <summary>A map of link names to associated URIs for additional resources or documentation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HubSpot.OpenApiClient.Models.CRM_Deal_Splits_BatchResponseDealToDealSplits_links? Links { get; set; }
#nullable restore
#else
        public global::Soenneker.HubSpot.OpenApiClient.Models.CRM_Deal_Splits_BatchResponseDealToDealSplits_links Links { get; set; }
#endif
        /// <summary>The timestamp indicating when the batch operation was requested, in date-time format.</summary>
        public DateTimeOffset? RequestedAt { get; set; }
        /// <summary>An array of deal-to-deal split objects representing the results of the batch operation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.HubSpot.OpenApiClient.Models.CRM_Deal_Splits_DealToDealSplits>? Results { get; set; }
#nullable restore
#else
        public List<global::Soenneker.HubSpot.OpenApiClient.Models.CRM_Deal_Splits_DealToDealSplits> Results { get; set; }
#endif
        /// <summary>The timestamp indicating when the batch operation started, in date-time format.</summary>
        public DateTimeOffset? StartedAt { get; set; }
        /// <summary>&quot;The current status of the batch operation, with possible values: CANCELED, COMPLETE, PENDING, PROCESSING.&quot;</summary>
        public global::Soenneker.HubSpot.OpenApiClient.Models.CRM_Deal_Splits_BatchResponseDealToDealSplits_status? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.CRM_Deal_Splits_BatchResponseDealToDealSplits"/> and sets the default values.
        /// </summary>
        public CRM_Deal_Splits_BatchResponseDealToDealSplits()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.CRM_Deal_Splits_BatchResponseDealToDealSplits"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HubSpot.OpenApiClient.Models.CRM_Deal_Splits_BatchResponseDealToDealSplits CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HubSpot.OpenApiClient.Models.CRM_Deal_Splits_BatchResponseDealToDealSplits();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "completedAt", n => { CompletedAt = n.GetDateTimeOffsetValue(); } },
                { "links", n => { Links = n.GetObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.CRM_Deal_Splits_BatchResponseDealToDealSplits_links>(global::Soenneker.HubSpot.OpenApiClient.Models.CRM_Deal_Splits_BatchResponseDealToDealSplits_links.CreateFromDiscriminatorValue); } },
                { "requestedAt", n => { RequestedAt = n.GetDateTimeOffsetValue(); } },
                { "results", n => { Results = n.GetCollectionOfObjectValues<global::Soenneker.HubSpot.OpenApiClient.Models.CRM_Deal_Splits_DealToDealSplits>(global::Soenneker.HubSpot.OpenApiClient.Models.CRM_Deal_Splits_DealToDealSplits.CreateFromDiscriminatorValue)?.AsList(); } },
                { "startedAt", n => { StartedAt = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.CRM_Deal_Splits_BatchResponseDealToDealSplits_status>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("completedAt", CompletedAt);
            writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.CRM_Deal_Splits_BatchResponseDealToDealSplits_links>("links", Links);
            writer.WriteDateTimeOffsetValue("requestedAt", RequestedAt);
            writer.WriteCollectionOfObjectValues<global::Soenneker.HubSpot.OpenApiClient.Models.CRM_Deal_Splits_DealToDealSplits>("results", Results);
            writer.WriteDateTimeOffsetValue("startedAt", StartedAt);
            writer.WriteEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.CRM_Deal_Splits_BatchResponseDealToDealSplits_status>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
