// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CRM_Lists_PublicDatePoint : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The day component of the date.</summary>
        public int? Day { get; set; }
        /// <summary>The hour component of the time.</summary>
        public int? Hour { get; set; }
        /// <summary>The millisecond component of the time.</summary>
        public int? Millisecond { get; set; }
        /// <summary>The minute component of the time.</summary>
        public int? Minute { get; set; }
        /// <summary>The month component of the date.</summary>
        public int? Month { get; set; }
        /// <summary>The second component of the time.</summary>
        public int? Second { get; set; }
        /// <summary>Specifies the type of time (DATE).</summary>
        public global::Soenneker.HubSpot.OpenApiClient.Models.CRM_Lists_PublicDatePoint_timeType? TimeType { get; set; }
        /// <summary>The source of the time zone information.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TimezoneSource { get; set; }
#nullable restore
#else
        public string TimezoneSource { get; set; }
#endif
        /// <summary>The year component of the date.</summary>
        public int? Year { get; set; }
        /// <summary>The identifier for the time zone.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ZoneId { get; set; }
#nullable restore
#else
        public string ZoneId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.CRM_Lists_PublicDatePoint"/> and sets the default values.
        /// </summary>
        public CRM_Lists_PublicDatePoint()
        {
            AdditionalData = new Dictionary<string, object>();
            TimeType = global::Soenneker.HubSpot.OpenApiClient.Models.CRM_Lists_PublicDatePoint_timeType.DATE;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.CRM_Lists_PublicDatePoint"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HubSpot.OpenApiClient.Models.CRM_Lists_PublicDatePoint CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HubSpot.OpenApiClient.Models.CRM_Lists_PublicDatePoint();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "day", n => { Day = n.GetIntValue(); } },
                { "hour", n => { Hour = n.GetIntValue(); } },
                { "millisecond", n => { Millisecond = n.GetIntValue(); } },
                { "minute", n => { Minute = n.GetIntValue(); } },
                { "month", n => { Month = n.GetIntValue(); } },
                { "second", n => { Second = n.GetIntValue(); } },
                { "timeType", n => { TimeType = n.GetEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.CRM_Lists_PublicDatePoint_timeType>(); } },
                { "timezoneSource", n => { TimezoneSource = n.GetStringValue(); } },
                { "year", n => { Year = n.GetIntValue(); } },
                { "zoneId", n => { ZoneId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("day", Day);
            writer.WriteIntValue("hour", Hour);
            writer.WriteIntValue("millisecond", Millisecond);
            writer.WriteIntValue("minute", Minute);
            writer.WriteIntValue("month", Month);
            writer.WriteIntValue("second", Second);
            writer.WriteEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.CRM_Lists_PublicDatePoint_timeType>("timeType", TimeType);
            writer.WriteStringValue("timezoneSource", TimezoneSource);
            writer.WriteIntValue("year", Year);
            writer.WriteStringValue("zoneId", ZoneId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
