// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Events_Manage_Event_Definitions_AbsoluteRangedTimestampRefineBy : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The lowerTimestamp property</summary>
        public int? LowerTimestamp { get; set; }
        /// <summary>The rangeType property</summary>
        public global::Soenneker.HubSpot.OpenApiClient.Models.Events_Manage_Event_Definitions_AbsoluteRangedTimestampRefineBy_rangeType? RangeType { get; set; }
        /// <summary>The type property</summary>
        public global::Soenneker.HubSpot.OpenApiClient.Models.Events_Manage_Event_Definitions_AbsoluteRangedTimestampRefineBy_type? Type { get; set; }
        /// <summary>The upperTimestamp property</summary>
        public int? UpperTimestamp { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.Events_Manage_Event_Definitions_AbsoluteRangedTimestampRefineBy"/> and sets the default values.
        /// </summary>
        public Events_Manage_Event_Definitions_AbsoluteRangedTimestampRefineBy()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.Events_Manage_Event_Definitions_AbsoluteRangedTimestampRefineBy"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HubSpot.OpenApiClient.Models.Events_Manage_Event_Definitions_AbsoluteRangedTimestampRefineBy CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HubSpot.OpenApiClient.Models.Events_Manage_Event_Definitions_AbsoluteRangedTimestampRefineBy();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "lowerTimestamp", n => { LowerTimestamp = n.GetIntValue(); } },
                { "rangeType", n => { RangeType = n.GetEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.Events_Manage_Event_Definitions_AbsoluteRangedTimestampRefineBy_rangeType>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.Events_Manage_Event_Definitions_AbsoluteRangedTimestampRefineBy_type>(); } },
                { "upperTimestamp", n => { UpperTimestamp = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("lowerTimestamp", LowerTimestamp);
            writer.WriteEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.Events_Manage_Event_Definitions_AbsoluteRangedTimestampRefineBy_rangeType>("rangeType", RangeType);
            writer.WriteEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.Events_Manage_Event_Definitions_AbsoluteRangedTimestampRefineBy_type>("type", Type);
            writer.WriteIntValue("upperTimestamp", UpperTimestamp);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
