// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Marketing_Forms_HubSpotFormConfiguration : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether to add a reset link to the form. This removes any pre-populated content on the form and creates a new contact on submission.</summary>
        public bool? AllowLinkToResetKnownValues { get; set; }
        /// <summary>Whether the form can be archived.</summary>
        public bool? Archivable { get; set; }
        /// <summary>Whether the form can be cloned.</summary>
        public bool? Cloneable { get; set; }
        /// <summary>Whether to create a new contact when a form is submitted with an email address that doesn’t match any in your existing contacts records.</summary>
        public bool? CreateNewContactForNewEmail { get; set; }
        /// <summary>Whether the form can be edited.</summary>
        public bool? Editable { get; set; }
        /// <summary>The embedType property</summary>
        public global::Soenneker.HubSpot.OpenApiClient.Models.Marketing_Forms_HubSpotFormConfiguration_embedType? EmbedType { get; set; }
        /// <summary>The language of the form.</summary>
        public global::Soenneker.HubSpot.OpenApiClient.Models.Marketing_Forms_HubSpotFormConfiguration_language? Language { get; set; }
        /// <summary>The lifecycleStages property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.HubSpot.OpenApiClient.Models.Marketing_Forms_LifecycleStage>? LifecycleStages { get; set; }
#nullable restore
#else
        public List<global::Soenneker.HubSpot.OpenApiClient.Models.Marketing_Forms_LifecycleStage> LifecycleStages { get; set; }
#endif
        /// <summary>Whether to send a notification email to the contact owner when a submission is received.</summary>
        public bool? NotifyContactOwner { get; set; }
        /// <summary>The list of user IDs to receive a notification email when a submission is received.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? NotifyRecipients { get; set; }
#nullable restore
#else
        public List<string> NotifyRecipients { get; set; }
#endif
        /// <summary>The postSubmitAction property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HubSpot.OpenApiClient.Models.Marketing_Forms_FormPostSubmitAction? PostSubmitAction { get; set; }
#nullable restore
#else
        public global::Soenneker.HubSpot.OpenApiClient.Models.Marketing_Forms_FormPostSubmitAction PostSubmitAction { get; set; }
#endif
        /// <summary>Whether contact fields should pre-populate with known information when a contact returns to your site.</summary>
        public bool? PrePopulateKnownValues { get; set; }
        /// <summary>Whether CAPTCHA (spam prevention) is enabled.</summary>
        public bool? RecaptchaEnabled { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.Marketing_Forms_HubSpotFormConfiguration"/> and sets the default values.
        /// </summary>
        public Marketing_Forms_HubSpotFormConfiguration()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.Marketing_Forms_HubSpotFormConfiguration"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HubSpot.OpenApiClient.Models.Marketing_Forms_HubSpotFormConfiguration CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HubSpot.OpenApiClient.Models.Marketing_Forms_HubSpotFormConfiguration();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allowLinkToResetKnownValues", n => { AllowLinkToResetKnownValues = n.GetBoolValue(); } },
                { "archivable", n => { Archivable = n.GetBoolValue(); } },
                { "cloneable", n => { Cloneable = n.GetBoolValue(); } },
                { "createNewContactForNewEmail", n => { CreateNewContactForNewEmail = n.GetBoolValue(); } },
                { "editable", n => { Editable = n.GetBoolValue(); } },
                { "embedType", n => { EmbedType = n.GetEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.Marketing_Forms_HubSpotFormConfiguration_embedType>(); } },
                { "language", n => { Language = n.GetEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.Marketing_Forms_HubSpotFormConfiguration_language>(); } },
                { "lifecycleStages", n => { LifecycleStages = n.GetCollectionOfObjectValues<global::Soenneker.HubSpot.OpenApiClient.Models.Marketing_Forms_LifecycleStage>(global::Soenneker.HubSpot.OpenApiClient.Models.Marketing_Forms_LifecycleStage.CreateFromDiscriminatorValue)?.AsList(); } },
                { "notifyContactOwner", n => { NotifyContactOwner = n.GetBoolValue(); } },
                { "notifyRecipients", n => { NotifyRecipients = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "postSubmitAction", n => { PostSubmitAction = n.GetObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.Marketing_Forms_FormPostSubmitAction>(global::Soenneker.HubSpot.OpenApiClient.Models.Marketing_Forms_FormPostSubmitAction.CreateFromDiscriminatorValue); } },
                { "prePopulateKnownValues", n => { PrePopulateKnownValues = n.GetBoolValue(); } },
                { "recaptchaEnabled", n => { RecaptchaEnabled = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("allowLinkToResetKnownValues", AllowLinkToResetKnownValues);
            writer.WriteBoolValue("archivable", Archivable);
            writer.WriteBoolValue("cloneable", Cloneable);
            writer.WriteBoolValue("createNewContactForNewEmail", CreateNewContactForNewEmail);
            writer.WriteBoolValue("editable", Editable);
            writer.WriteEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.Marketing_Forms_HubSpotFormConfiguration_embedType>("embedType", EmbedType);
            writer.WriteEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.Marketing_Forms_HubSpotFormConfiguration_language>("language", Language);
            writer.WriteCollectionOfObjectValues<global::Soenneker.HubSpot.OpenApiClient.Models.Marketing_Forms_LifecycleStage>("lifecycleStages", LifecycleStages);
            writer.WriteBoolValue("notifyContactOwner", NotifyContactOwner);
            writer.WriteCollectionOfPrimitiveValues<string>("notifyRecipients", NotifyRecipients);
            writer.WriteObjectValue<global::Soenneker.HubSpot.OpenApiClient.Models.Marketing_Forms_FormPostSubmitAction>("postSubmitAction", PostSubmitAction);
            writer.WriteBoolValue("prePopulateKnownValues", PrePopulateKnownValues);
            writer.WriteBoolValue("recaptchaEnabled", RecaptchaEnabled);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
