// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Marketing_Forms_DependentFieldFilter : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The comparison operator used to evaluate the dependent field condition. Supports equality (eq, neq), string operations (contains, doesnt_contain, str_starts_with, str_ends_with), numeric comparisons (lt, lte, gt, gte), range checks (between, not_between), set operations (set_any, set_not_any, set_eq, set_neq), and time-based conditions (within_time, within_time_reverse).</summary>
        public global::Soenneker.HubSpot.OpenApiClient.Models.Marketing_Forms_DependentFieldFilter_operator? Operator { get; set; }
        /// <summary>The end value for range-based operators (between, not_between). Must be provided together with rangeStart.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RangeEnd { get; set; }
#nullable restore
#else
        public string RangeEnd { get; set; }
#endif
        /// <summary>The start value for range-based operators (between, not_between). Must be provided together with rangeEnd.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RangeStart { get; set; }
#nullable restore
#else
        public string RangeStart { get; set; }
#endif
        /// <summary>The single value to compare against when using operators like eq, neq, contains, lt, gt, and other single-value comparison operators.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Value { get; set; }
#nullable restore
#else
        public string Value { get; set; }
#endif
        /// <summary>The values property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Values { get; set; }
#nullable restore
#else
        public List<string> Values { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.Marketing_Forms_DependentFieldFilter"/> and sets the default values.
        /// </summary>
        public Marketing_Forms_DependentFieldFilter()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HubSpot.OpenApiClient.Models.Marketing_Forms_DependentFieldFilter"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HubSpot.OpenApiClient.Models.Marketing_Forms_DependentFieldFilter CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HubSpot.OpenApiClient.Models.Marketing_Forms_DependentFieldFilter();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "operator", n => { Operator = n.GetEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.Marketing_Forms_DependentFieldFilter_operator>(); } },
                { "rangeEnd", n => { RangeEnd = n.GetStringValue(); } },
                { "rangeStart", n => { RangeStart = n.GetStringValue(); } },
                { "value", n => { Value = n.GetStringValue(); } },
                { "values", n => { Values = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.HubSpot.OpenApiClient.Models.Marketing_Forms_DependentFieldFilter_operator>("operator", Operator);
            writer.WriteStringValue("rangeEnd", RangeEnd);
            writer.WriteStringValue("rangeStart", RangeStart);
            writer.WriteStringValue("value", Value);
            writer.WriteCollectionOfPrimitiveValues<string>("values", Values);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
