// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Models
{
    /// <summary>The field type identifier.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Marketing_Forms_PaymentLinkRadioField_fieldType
    {
        [EnumMember(Value = "payment_link_radio")]
        #pragma warning disable CS1591
        Payment_link_radio,
        #pragma warning restore CS1591
    }
}
