// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.HubSpot.OpenApiClient.Crm.V3.Lists.Item.SizeAndEditsHistory.Between;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.HubSpot.OpenApiClient.Crm.V3.Lists.Item.SizeAndEditsHistory
{
    /// <summary>
    /// Builds and executes requests for operations under \crm\v3\lists\{listId}\size-and-edits-history
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SizeAndEditsHistoryRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The between property</summary>
        public global::Soenneker.HubSpot.OpenApiClient.Crm.V3.Lists.Item.SizeAndEditsHistory.Between.BetweenRequestBuilder Between
        {
            get => new global::Soenneker.HubSpot.OpenApiClient.Crm.V3.Lists.Item.SizeAndEditsHistory.Between.BetweenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HubSpot.OpenApiClient.Crm.V3.Lists.Item.SizeAndEditsHistory.SizeAndEditsHistoryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SizeAndEditsHistoryRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/crm/v3/lists/{listId}/size-and-edits-history", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HubSpot.OpenApiClient.Crm.V3.Lists.Item.SizeAndEditsHistory.SizeAndEditsHistoryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SizeAndEditsHistoryRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/crm/v3/lists/{listId}/size-and-edits-history", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
